//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por la herramienta GeneradorCodigo.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto 
//     y se perderán si se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Collections.Generic;
using Iberdrola.Commons.DataAccess;
using Iberdrola.SMG.DAL.DTO;
using Iberdrola.SMG.DAL.DB;

namespace Iberdrola.SMG.BLL
{
    /// <summary>
    /// Métodos de acceso a base de datos para la entidad PCamposPdfContratoGasConfort
    /// </summary>
    public partial class PCamposPdfContratoGasConfort
    {
        /// <summary>
        /// Obtiene el PCamposPdfContratoGasConfortDTO que cumple con la PK y no esté de baja
        /// </summary>
        /// <param name="idCampo"></param>
        /// <returns>PCamposPdfContratoGasConfortDTO que cumple con la PK, null si no lo encuentra.</returns>
        public static PCamposPdfContratoGasConfortDTO Obtener(decimal idCampo)
        {
            PCamposPdfContratoGasConfortDB db = new PCamposPdfContratoGasConfortDB();
            return db.Obtener(idCampo);
        }
        
        /// <summary>
        /// Obtiene todos PCamposPdfContratoGasConfortDTO que no estén de baja
        /// </summary>
        /// <returns>Lista de PCamposPdfContratoGasConfortDTO con todos los objetos</returns>
        public static List<PCamposPdfContratoGasConfortDTO> ObtenerTodos()
        {
            PCamposPdfContratoGasConfortDB db = new PCamposPdfContratoGasConfortDB();
            return db.ObtenerTodos();
        }
        
        /// <summary>
        /// Inserta el PCamposPdfContratoGasConfortDTO
        /// </summary>
        /// <param name="dto">Datos a guardar</param>
        /// <returns>PCamposPdfContratoGasConfortDTO con la clave autogenerada informada (si la tuviera)</returns>
        public static PCamposPdfContratoGasConfortDTO Insertar(PCamposPdfContratoGasConfortDTO dto)
        {
            PCamposPdfContratoGasConfortDB db = new PCamposPdfContratoGasConfortDB();
            return db.Insertar(dto);
        }
        
        /// <summary>
        /// Actualiza el PCamposPdfContratoGasConfortDTO
        /// </summary>
        /// <param name="dto">Datos a actualizar</param>
        /// <returns>int con el número de filas actualizadas</returns>
        public static int Actualizar(PCamposPdfContratoGasConfortDTO dto)
        {
            PCamposPdfContratoGasConfortDB db = new PCamposPdfContratoGasConfortDB();
            return db.Actualizar(dto);
        }
        
        /// <summary>
        /// Elimina el PCamposPdfContratoGasConfortDTO. si el objeto tiene un campo de fecha baja
        /// para hacer bajas lógicas realiza un borrado lógico
        /// </summary>
        /// <param name="idCampo"></param>
        /// <returns>int con el número de filas eliminadas</returns>
        public static int Eliminar(decimal idCampo)
        {
            PCamposPdfContratoGasConfortDB db = new PCamposPdfContratoGasConfortDB();
            return db.Eliminar(idCampo);
        }

        /// <summary>
        /// Obtiene los PCamposPdfContratoGasConfortDTO que cumple con la el criterio de búsqueda y no está de baja
        /// </summary>
        /// <param name="dtoFiltro">Filtro de PCamposPdfContratoGasConfort a aplicar</param>
        /// <param name="paginacion">Datos de la paginación</param>
        /// <returns>Lista de PCamposPdfContratoGasConfortDTO que cumplen con los filtros indicados.</returns>
        public static List<PCamposPdfContratoGasConfortDTO> Buscar(PCamposPdfContratoGasConfortDTO dtoFiltro, Pagination paginacion)
        {
            PCamposPdfContratoGasConfortDB db = new PCamposPdfContratoGasConfortDB();
            return db.Buscar(dtoFiltro, paginacion);
        } 

        /// <summary>
        /// Obtiene los el número de registros que cumple con la el criterio de búsqueda y no está de baja
        /// </summary>
        /// <param name="dtoFiltro">Filtro de PCamposPdfContratoGasConfort a aplicar</param>
        /// <returns>PCamposPdfContratoGasConfortEntero con el número de registros.</returns>
        public static int BuscarNumReg(PCamposPdfContratoGasConfortDTO dtoFiltro)
        {
            PCamposPdfContratoGasConfortDB db = new PCamposPdfContratoGasConfortDB();
            return db.BuscarNumReg(dtoFiltro);
        }           
    }
}