//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por la herramienta GeneradorCodigo.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto 
//     y se perderán si se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Collections.Generic;
using Iberdrola.Commons.DataAccess;
using Iberdrola.SMG.DAL.DTO;
using Iberdrola.SMG.DAL.DB;

namespace Iberdrola.SMG.BLL
{
    /// <summary>
    /// Métodos de acceso a base de datos para la entidad PMapeoEtiquetasDocumentosConCamposBbdd
    /// </summary>
    public partial class PMapeoEtiquetasDocumentosConCamposBbdd
    {
        /// <summary>
        /// Obtiene el PMapeoEtiquetasDocumentosConCamposBbddDTO que cumple con la PK y no esté de baja
        /// </summary>
        /// <param name="idCampo"></param>
        /// <returns>PMapeoEtiquetasDocumentosConCamposBbddDTO que cumple con la PK, null si no lo encuentra.</returns>
        public static PMapeoEtiquetasDocumentosConCamposBbddDTO Obtener(decimal idCampo)
        {
            PMapeoEtiquetasDocumentosConCamposBbddDB db = new PMapeoEtiquetasDocumentosConCamposBbddDB();
            return db.Obtener(idCampo);
        }
        
        /// <summary>
        /// Obtiene todos PMapeoEtiquetasDocumentosConCamposBbddDTO que no estén de baja
        /// </summary>
        /// <returns>Lista de PMapeoEtiquetasDocumentosConCamposBbddDTO con todos los objetos</returns>
        public static List<PMapeoEtiquetasDocumentosConCamposBbddDTO> ObtenerTodos()
        {
            PMapeoEtiquetasDocumentosConCamposBbddDB db = new PMapeoEtiquetasDocumentosConCamposBbddDB();
            return db.ObtenerTodos();
        }
        
        /// <summary>
        /// Inserta el PMapeoEtiquetasDocumentosConCamposBbddDTO
        /// </summary>
        /// <param name="dto">Datos a guardar</param>
        /// <returns>PMapeoEtiquetasDocumentosConCamposBbddDTO con la clave autogenerada informada (si la tuviera)</returns>
        public static PMapeoEtiquetasDocumentosConCamposBbddDTO Insertar(PMapeoEtiquetasDocumentosConCamposBbddDTO dto)
        {
            PMapeoEtiquetasDocumentosConCamposBbddDB db = new PMapeoEtiquetasDocumentosConCamposBbddDB();
            return db.Insertar(dto);
        }
        
        /// <summary>
        /// Actualiza el PMapeoEtiquetasDocumentosConCamposBbddDTO
        /// </summary>
        /// <param name="dto">Datos a actualizar</param>
        /// <returns>int con el número de filas actualizadas</returns>
        public static int Actualizar(PMapeoEtiquetasDocumentosConCamposBbddDTO dto)
        {
            PMapeoEtiquetasDocumentosConCamposBbddDB db = new PMapeoEtiquetasDocumentosConCamposBbddDB();
            return db.Actualizar(dto);
        }
        
        /// <summary>
        /// Elimina el PMapeoEtiquetasDocumentosConCamposBbddDTO. si el objeto tiene un campo de fecha baja
        /// para hacer bajas lógicas realiza un borrado lógico
        /// </summary>
        /// <param name="idCampo"></param>
        /// <returns>int con el número de filas eliminadas</returns>
        public static int Eliminar(decimal idCampo)
        {
            PMapeoEtiquetasDocumentosConCamposBbddDB db = new PMapeoEtiquetasDocumentosConCamposBbddDB();
            return db.Eliminar(idCampo);
        }

        /// <summary>
        /// Obtiene los PMapeoEtiquetasDocumentosConCamposBbddDTO que cumple con la el criterio de búsqueda y no está de baja
        /// </summary>
        /// <param name="dtoFiltro">Filtro de PMapeoEtiquetasDocumentosConCamposBbdd a aplicar</param>
        /// <param name="paginacion">Datos de la paginación</param>
        /// <returns>Lista de PMapeoEtiquetasDocumentosConCamposBbddDTO que cumplen con los filtros indicados.</returns>
        public static List<PMapeoEtiquetasDocumentosConCamposBbddDTO> Buscar(PMapeoEtiquetasDocumentosConCamposBbddDTO dtoFiltro, Pagination paginacion)
        {
            PMapeoEtiquetasDocumentosConCamposBbddDB db = new PMapeoEtiquetasDocumentosConCamposBbddDB();
            return db.Buscar(dtoFiltro, paginacion);
        } 

        /// <summary>
        /// Obtiene los el número de registros que cumple con la el criterio de búsqueda y no está de baja
        /// </summary>
        /// <param name="dtoFiltro">Filtro de PMapeoEtiquetasDocumentosConCamposBbdd a aplicar</param>
        /// <returns>PMapeoEtiquetasDocumentosConCamposBbddEntero con el número de registros.</returns>
        public static int BuscarNumReg(PMapeoEtiquetasDocumentosConCamposBbddDTO dtoFiltro)
        {
            PMapeoEtiquetasDocumentosConCamposBbddDB db = new PMapeoEtiquetasDocumentosConCamposBbddDB();
            return db.BuscarNumReg(dtoFiltro);
        }           
    }
}