//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por la herramienta GeneradorCodigo.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto 
//     y se perderán si se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Collections.Generic;
using Iberdrola.Commons.DataAccess;
using Iberdrola.SMG.DAL.DTO;
using Iberdrola.SMG.DAL.DB;

namespace Iberdrola.SMG.BLL
{
    /// <summary>
    /// Métodos de acceso a base de datos para la entidad PValidacionesTicketCombustion
    /// </summary>
    public partial class PValidacionesTicketCombustion
    {
        /// <summary>
        /// Obtiene el PValidacionesTicketCombustionDTO que cumple con la PK y no esté de baja
        /// </summary>
        /// <param name="idValidacion"></param>
        /// <returns>PValidacionesTicketCombustionDTO que cumple con la PK, null si no lo encuentra.</returns>
        public static PValidacionesTicketCombustionDTO Obtener(decimal idValidacion)
        {
            PValidacionesTicketCombustionDB db = new PValidacionesTicketCombustionDB();
            return db.Obtener(idValidacion);
        }
        
        /// <summary>
        /// Obtiene todos PValidacionesTicketCombustionDTO que no estén de baja
        /// </summary>
        /// <returns>Lista de PValidacionesTicketCombustionDTO con todos los objetos</returns>
        public static List<PValidacionesTicketCombustionDTO> ObtenerTodos()
        {
            PValidacionesTicketCombustionDB db = new PValidacionesTicketCombustionDB();
            return db.ObtenerTodos();
        }
        
        /// <summary>
        /// Inserta el PValidacionesTicketCombustionDTO
        /// </summary>
        /// <param name="dto">Datos a guardar</param>
        /// <returns>PValidacionesTicketCombustionDTO con la clave autogenerada informada (si la tuviera)</returns>
        public static PValidacionesTicketCombustionDTO Insertar(PValidacionesTicketCombustionDTO dto)
        {
            PValidacionesTicketCombustionDB db = new PValidacionesTicketCombustionDB();
            return db.Insertar(dto);
        }
        
        /// <summary>
        /// Actualiza el PValidacionesTicketCombustionDTO
        /// </summary>
        /// <param name="dto">Datos a actualizar</param>
        /// <returns>int con el número de filas actualizadas</returns>
        public static int Actualizar(PValidacionesTicketCombustionDTO dto)
        {
            PValidacionesTicketCombustionDB db = new PValidacionesTicketCombustionDB();
            return db.Actualizar(dto);
        }
        
        /// <summary>
        /// Elimina el PValidacionesTicketCombustionDTO. si el objeto tiene un campo de fecha baja
        /// para hacer bajas lógicas realiza un borrado lógico
        /// </summary>
        /// <param name="idValidacion"></param>
        /// <returns>int con el número de filas eliminadas</returns>
        public static int Eliminar(decimal idValidacion)
        {
            PValidacionesTicketCombustionDB db = new PValidacionesTicketCombustionDB();
            return db.Eliminar(idValidacion);
        }

        /// <summary>
        /// Obtiene los PValidacionesTicketCombustionDTO que cumple con la el criterio de búsqueda y no está de baja
        /// </summary>
        /// <param name="dtoFiltro">Filtro de PValidacionesTicketCombustion a aplicar</param>
        /// <param name="paginacion">Datos de la paginación</param>
        /// <returns>Lista de PValidacionesTicketCombustionDTO que cumplen con los filtros indicados.</returns>
        public static List<PValidacionesTicketCombustionDTO> Buscar(PValidacionesTicketCombustionDTO dtoFiltro, Pagination paginacion)
        {
            PValidacionesTicketCombustionDB db = new PValidacionesTicketCombustionDB();
            return db.Buscar(dtoFiltro, paginacion);
        } 

        /// <summary>
        /// Obtiene los el número de registros que cumple con la el criterio de búsqueda y no está de baja
        /// </summary>
        /// <param name="dtoFiltro">Filtro de PValidacionesTicketCombustion a aplicar</param>
        /// <returns>PValidacionesTicketCombustionEntero con el número de registros.</returns>
        public static int BuscarNumReg(PValidacionesTicketCombustionDTO dtoFiltro)
        {
            PValidacionesTicketCombustionDB db = new PValidacionesTicketCombustionDB();
            return db.BuscarNumReg(dtoFiltro);
        }           
    }
}