//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por la herramienta GeneradorCodigo.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto 
//     y se perderán si se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Data;
using Iberdrola.Commons.BaseClasses;
using Iberdrola.Commons.DataAccess;
using Iberdrola.Commons.Exceptions;
using Iberdrola.Commons.Messages;
using Iberdrola.SMG.DAL.DTO;

namespace Iberdrola.SMG.DAL.DB
{
    /// <summary>
    /// Métodos de acceso a base de datos para la entidad PMapeoEtiquetasDocumentosConCamposBbdd
    /// </summary>
    public partial class PMapeoEtiquetasDocumentosConCamposBbddDB
    {
        /// <summary>
        /// Obtiene el PMapeoEtiquetasDocumentosConCamposBbddDTO que cumple con la PK y no esté de baja
        /// </summary>
        /// <param name="idCampo"></param>
        /// <returns>PMapeoEtiquetasDocumentosConCamposBbddDTO que cumple con la PK, null si no lo encuentra.</returns>
        public PMapeoEtiquetasDocumentosConCamposBbddDTO Obtener(decimal idCampo)
        {
            IDataReader dr = null;
            PMapeoEtiquetasDocumentosConCamposBbddDTO dto = null;
            
            try
            {
                DataBaseLibrary db = new DataBaseLibrary(BaseDB.SMG_DB);

                string[] aNombres = new string[1];
                DbType[] aTipos = new DbType[1];
                object[] aValores = new object[1];
                
                aNombres[0] = "@pID_CAMPO";
                aTipos[0] = DbType.Decimal;
                aValores[0] = idCampo;
                
                

                // Hacemos la llamada a la base de datos
                dr = db.RunProcDataReader("spSMGPMapeoEtiquetasDocumentosConCamposBbddGet", aNombres, aTipos, aValores);
                
                // Rebuperamos el objeto buscado
                if (dr.Read())
                {
                    dto = ObtenerPMapeoEtiquetasDocumentosConCamposBbddDTO(dr);
                }
            }
            catch (BaseException)
            {
                throw;
            }
            catch (Exception ex)
            {
                throw new DALException(false, ex, "2004");
            }
            finally
            {
                if (dr != null)
                {
                    dr.Close();
                }
            }
            
            // retornamos el objeto buscado, si no se ha encontrato nada se retorna null
            return dto;
        }
        
        /// <summary>
        /// Obtiene todos PMapeoEtiquetasDocumentosConCamposBbddDTO que no estén de baja
        /// </summary>
        /// <returns>Lista de PMapeoEtiquetasDocumentosConCamposBbddDTO con todos los objetos</returns>
        public List<PMapeoEtiquetasDocumentosConCamposBbddDTO> ObtenerTodos()
        {
            IDataReader dr = null;            
            List<PMapeoEtiquetasDocumentosConCamposBbddDTO> lista = null;
            
            try
            {
                DataBaseLibrary db = new DataBaseLibrary(BaseDB.SMG_DB);
                lista = new List<PMapeoEtiquetasDocumentosConCamposBbddDTO>();

                // Hacemos la llamada a la base de datos
                dr = db.RunProcDataReader("spSMGPMapeoEtiquetasDocumentosConCamposBbddGetAll", null, null, null);

                // Recuperamos la lista de objetos encontrados.
                while (dr.Read())
                {
                    lista.Add(ObtenerPMapeoEtiquetasDocumentosConCamposBbddDTO(dr));
                }
            }
            catch (BaseException)
            {
                throw;
            }
            catch (Exception ex)
            {
                throw new DALException(false, ex, "2004");
            }
            finally
            {
                if (dr != null)
                {
                    dr.Close();
                }
            }

            // retornamos la lista de objetos buscados, si no se ha encontrato nada se retorna null
            return lista;
        }
        
        /// <summary>
        /// Inserta el PMapeoEtiquetasDocumentosConCamposBbddDTO
        /// </summary>
        /// <param name="dto">Datos a guardar</param>
        /// <returns>PMapeoEtiquetasDocumentosConCamposBbddDTO con la clave autogenerada informada (si la tuviera)</returns>
        public PMapeoEtiquetasDocumentosConCamposBbddDTO Insertar(PMapeoEtiquetasDocumentosConCamposBbddDTO dto)
        {
            try
            {
                DataBaseLibrary db = new DataBaseLibrary(BaseDB.SMG_DB);
                
                string[] aNombres = new string[7];
                DbType[] aTipos = new DbType[7];
                object[] aValores = new object[7];
                
                aNombres[0] = "@pNOMBRE_PROCESO";
                aTipos[0] = DbType.String;
                aValores[0] = dto.NombreProceso;
                
                aNombres[1] = "@pACTIVO";
                aTipos[1] = DbType.Boolean;
                aValores[1] = dto.Activo;
                
                aNombres[2] = "@pNOMBRE_ETIQUETA_SUSTITUIR";
                aTipos[2] = DbType.String;
                aValores[2] = dto.NombreEtiquetaSustituir;
                
                aNombres[3] = "@pTABLA_ORIGEN_CAMPO";
                aTipos[3] = DbType.String;
                aValores[3] = dto.TablaOrigenCampo;
                
                aNombres[4] = "@pNOMBRE_CAMPO";
                aTipos[4] = DbType.String;
                aValores[4] = dto.NombreCampo;
                
                aNombres[5] = "@pTIPO_DATO";
                aTipos[5] = DbType.String;
                aValores[5] = dto.TipoDato;
                
                aNombres[6] = "@pFORMATO_ETIQUETA_SUSTITUIR";
                aTipos[6] = DbType.String;
                aValores[6] = dto.FormatoEtiquetaSustituir;
                
                

                // Hacemos la llamada a la base de datos
                object result = db.RunProcEscalar("spSMGPMapeoEtiquetasDocumentosConCamposBbddInsert", aNombres, aTipos, aValores);
                dto.IdCampo = (decimal)result;

            }
            catch (BaseException)
            {
                throw;
            }
            catch (Exception ex)
            {
                throw new DALException(false, ex, "2005");
            }
            return dto;
        }
                
        /// <summary>
        /// Actualiza el PMapeoEtiquetasDocumentosConCamposBbddDTO
        /// </summary>
        /// <param name="dto">Datos a actualizar</param>
        /// <returns>int con el número de filas actualizadas</returns>
        public int Actualizar(PMapeoEtiquetasDocumentosConCamposBbddDTO dto)
        {
            try
            {
                DataBaseLibrary db = new DataBaseLibrary(BaseDB.SMG_DB);
                
                string[] aNombres = new string[8];
                DbType[] aTipos = new DbType[8];
                object[] aValores = new object[8];
                
                aNombres[0] = "@pID_CAMPO";
                aTipos[0] = DbType.Decimal;
                aValores[0] = dto.IdCampo;
                
                aNombres[1] = "@pNOMBRE_PROCESO";
                aTipos[1] = DbType.String;
                aValores[1] = dto.NombreProceso;
                
                aNombres[2] = "@pACTIVO";
                aTipos[2] = DbType.Boolean;
                aValores[2] = dto.Activo;
                
                aNombres[3] = "@pNOMBRE_ETIQUETA_SUSTITUIR";
                aTipos[3] = DbType.String;
                aValores[3] = dto.NombreEtiquetaSustituir;
                
                aNombres[4] = "@pTABLA_ORIGEN_CAMPO";
                aTipos[4] = DbType.String;
                aValores[4] = dto.TablaOrigenCampo;
                
                aNombres[5] = "@pNOMBRE_CAMPO";
                aTipos[5] = DbType.String;
                aValores[5] = dto.NombreCampo;
                
                aNombres[6] = "@pTIPO_DATO";
                aTipos[6] = DbType.String;
                aValores[6] = dto.TipoDato;
                
                aNombres[7] = "@pFORMATO_ETIQUETA_SUSTITUIR";
                aTipos[7] = DbType.String;
                aValores[7] = dto.FormatoEtiquetaSustituir;
                
                

                // Hacemos la llamada a la base de datos
                object result = db.RunProcEscalar("spSMGPMapeoEtiquetasDocumentosConCamposBbddUpdate", aNombres, aTipos, aValores);
                
                // Retornamos el número de filas afectadas.
                return (int) result;
            }
            catch (BaseException)
            {
                throw;
            }
            catch (Exception ex)
            {
                throw new DALException(false, ex, "2005");
            }
        }
        
        /// <summary>
        /// Elimina el PMapeoEtiquetasDocumentosConCamposBbddDTO. si el objeto tiene un campo de fecha baja
        /// para hacer bajas lógicas realiza un borrado lógico
        /// </summary>
        /// <param name="idCampo"></param>
        /// <returns>int con el número de filas eliminadas</returns>
        public int Eliminar(decimal idCampo)
        {
            try
            {
                DataBaseLibrary db = new DataBaseLibrary(BaseDB.SMG_DB);

                string[] aNombres = new string[1];
                DbType[] aTipos = new DbType[1];
                object[] aValores = new object[1];
                
                aNombres[0] = "@pID_CAMPO";
                aTipos[0] = DbType.Decimal;
                aValores[0] = idCampo;
                
                

                // Hacemos la llamada a la base de datos
                object result = db.RunProcEscalar("spSMGPMapeoEtiquetasDocumentosConCamposBbddDelete", aNombres, aTipos, aValores);

                // Retornamos el número de filas afectadas.
                return (int) result;
            }
            catch (BaseException)
            {
                throw;
            }
            catch (Exception ex)
            {
                throw new DALException(false, ex, "2004");
            }
        }

        /// <summary>
        /// Obtiene los PMapeoEtiquetasDocumentosConCamposBbddDTO que cumple con la el criterio de búsqueda y no está de baja
        /// </summary>
        /// <param name="dtoFiltro">Filtro de PMapeoEtiquetasDocumentosConCamposBbdd a aplicar</param>
        /// <param name="paginacion">Datos de la paginación</param>
        /// <returns>Lista de PMapeoEtiquetasDocumentosConCamposBbddDTO que cumplen con los filtros indicados.</returns>
        public List<PMapeoEtiquetasDocumentosConCamposBbddDTO> Buscar(PMapeoEtiquetasDocumentosConCamposBbddDTO dtoFiltro, Pagination paginacion)
        {

            IDataReader dr = null;            
            List<PMapeoEtiquetasDocumentosConCamposBbddDTO> lista = null;
            
            try
            {
                DataBaseLibrary db = new DataBaseLibrary(BaseDB.SMG_DB);
                lista = new List<PMapeoEtiquetasDocumentosConCamposBbddDTO>();

                string[] aNombres = new string[10];
                DbType[] aTipos = new DbType[10];
                object[] aValores = new object[10];
                
                aNombres[0] = "@pNOMBRE_PROCESO";
                aTipos[0] = DbType.String;
                aValores[0] = dtoFiltro.NombreProceso;
                
                aNombres[1] = "@pACTIVO";
                aTipos[1] = DbType.Boolean;
                aValores[1] = dtoFiltro.Activo;
                
                aNombres[2] = "@pNOMBRE_ETIQUETA_SUSTITUIR";
                aTipos[2] = DbType.String;
                aValores[2] = dtoFiltro.NombreEtiquetaSustituir;
                
                aNombres[3] = "@pTABLA_ORIGEN_CAMPO";
                aTipos[3] = DbType.String;
                aValores[3] = dtoFiltro.TablaOrigenCampo;
                
                aNombres[4] = "@pNOMBRE_CAMPO";
                aTipos[4] = DbType.String;
                aValores[4] = dtoFiltro.NombreCampo;
                
                aNombres[5] = "@pTIPO_DATO";
                aTipos[5] = DbType.String;
                aValores[5] = dtoFiltro.TipoDato;
                
                aNombres[6] = "@pFORMATO_ETIQUETA_SUSTITUIR";
                aTipos[6] = DbType.String;
                aValores[6] = dtoFiltro.FormatoEtiquetaSustituir;
                
                aNombres[7] = "@pPAGE_INDEX";
                aTipos[7] = DbType.Int32;
                aValores[7] = paginacion.PaginaActual;
                
                aNombres[8] = "@pSORT_FIELD";
                aTipos[8] = DbType.String;
                aValores[8] = paginacion.CampoOrden;
                
                aNombres[9] = "@pSORT_ORDER";
                aTipos[9] = DbType.String;
                aValores[9] = paginacion.DireccionOrden;
                
                

                // Hacemos la llamada a la base de datos
                dr = db.RunProcDataReader("spSMGPMapeoEtiquetasDocumentosConCamposBbddFind", aNombres, aTipos, aValores);

                // Recuperamos la lista de objetos encontrados.
                while (dr.Read())
                {
                    lista.Add(ObtenerPMapeoEtiquetasDocumentosConCamposBbddDTO(dr));
                }
                return lista;
            }
            catch (BaseException)
            {
                throw;
            }
            catch (Exception ex)
            {
                throw new DALException(false, ex, "2004");
            }
            finally
            {
                if (dr != null)
                {
                    dr.Close();
                }
            }            
        }


        /// <summary>
        /// Obtiene los el número de registros que cumple con la el criterio de búsqueda y no está de baja
        /// </summary>
        /// <param name="dtoFiltro">Filtro de PMapeoEtiquetasDocumentosConCamposBbdd a aplicar</param>
        /// <returns>PMapeoEtiquetasDocumentosConCamposBbddEntero con el número de registros.</returns>
        public int BuscarNumReg(PMapeoEtiquetasDocumentosConCamposBbddDTO dtoFiltro)
        {
            try
            {
                DataBaseLibrary db = new DataBaseLibrary(BaseDB.SMG_DB);

                string[] aNombres = new string[7];
                DbType[] aTipos = new DbType[7];
                object[] aValores = new object[7];
                
                aNombres[0] = "@pNOMBRE_PROCESO";
                aTipos[0] = DbType.String;
                aValores[0] = dtoFiltro.NombreProceso;
                
                aNombres[1] = "@pACTIVO";
                aTipos[1] = DbType.Boolean;
                aValores[1] = dtoFiltro.Activo;
                
                aNombres[2] = "@pNOMBRE_ETIQUETA_SUSTITUIR";
                aTipos[2] = DbType.String;
                aValores[2] = dtoFiltro.NombreEtiquetaSustituir;
                
                aNombres[3] = "@pTABLA_ORIGEN_CAMPO";
                aTipos[3] = DbType.String;
                aValores[3] = dtoFiltro.TablaOrigenCampo;
                
                aNombres[4] = "@pNOMBRE_CAMPO";
                aTipos[4] = DbType.String;
                aValores[4] = dtoFiltro.NombreCampo;
                
                aNombres[5] = "@pTIPO_DATO";
                aTipos[5] = DbType.String;
                aValores[5] = dtoFiltro.TipoDato;
                
                aNombres[6] = "@pFORMATO_ETIQUETA_SUSTITUIR";
                aTipos[6] = DbType.String;
                aValores[6] = dtoFiltro.FormatoEtiquetaSustituir;
                
                

                // Hacemos la llamada a la base de datos y retornamos el resultado
                return (int) db.RunProcEscalar("spSMGPMapeoEtiquetasDocumentosConCamposBbddFindNumReg", aNombres, aTipos, aValores);
            }
            catch (BaseException)
            {
                throw;
            }
            catch (Exception ex)
            {
                throw new DALException(false, ex, "2004");
            }
        }

        /// <summary>
        /// Carga los datos del IDataReader en un objeto PMapeoEtiquetasDocumentosConCamposBbddDTO
        /// </summary>
        /// <param name="dr">DataReader con los datos obtenidos de la BBDD</param>
        /// <returns>PMapeoEtiquetasDocumentosConCamposBbddDTO con los datos cargados</returns>
        private PMapeoEtiquetasDocumentosConCamposBbddDTO ObtenerPMapeoEtiquetasDocumentosConCamposBbddDTO(IDataReader dr)
        {
            PMapeoEtiquetasDocumentosConCamposBbddDTO dto = new PMapeoEtiquetasDocumentosConCamposBbddDTO();
            if (DataBaseUtils.HasColumn(dr, "ID_CAMPO"))
            {
				dto.IdCampo = (decimal)DataBaseUtils.GetDataReaderColumnValue(dr, "ID_CAMPO");
            }         
			if (DataBaseUtils.HasColumn(dr, "NOMBRE_PROCESO"))
            {
				dto.NombreProceso = (string)DataBaseUtils.GetDataReaderColumnValue(dr, "NOMBRE_PROCESO");
            }         
			if (DataBaseUtils.HasColumn(dr, "ACTIVO"))
            {
				dto.Activo = (bool?)DataBaseUtils.GetDataReaderColumnValue(dr, "ACTIVO");
            }         
			if (DataBaseUtils.HasColumn(dr, "NOMBRE_ETIQUETA_SUSTITUIR"))
            {
				dto.NombreEtiquetaSustituir = (string)DataBaseUtils.GetDataReaderColumnValue(dr, "NOMBRE_ETIQUETA_SUSTITUIR");
            }         
			if (DataBaseUtils.HasColumn(dr, "TABLA_ORIGEN_CAMPO"))
            {
				dto.TablaOrigenCampo = (string)DataBaseUtils.GetDataReaderColumnValue(dr, "TABLA_ORIGEN_CAMPO");
            }         
			if (DataBaseUtils.HasColumn(dr, "NOMBRE_CAMPO"))
            {
				dto.NombreCampo = (string)DataBaseUtils.GetDataReaderColumnValue(dr, "NOMBRE_CAMPO");
            }         
			if (DataBaseUtils.HasColumn(dr, "TIPO_DATO"))
            {
				dto.TipoDato = (string)DataBaseUtils.GetDataReaderColumnValue(dr, "TIPO_DATO");
            }         
			if (DataBaseUtils.HasColumn(dr, "FORMATO_ETIQUETA_SUSTITUIR"))
            {
				dto.FormatoEtiquetaSustituir = (string)DataBaseUtils.GetDataReaderColumnValue(dr, "FORMATO_ETIQUETA_SUSTITUIR");
            }         
			
            return dto;
        }

    }
}