//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por la herramienta GeneradorCodigo.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto 
//     y se perderán si se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using Iberdrola.Commons.BaseClasses;

namespace Iberdrola.SMG.DAL.DTO
{
    /// <summary>
    /// Atributos y Propiedades de la entidad PCamposPdfContratoGasConfort
    /// </summary>
    public partial class PCamposPdfContratoGasConfortDTO
    {
        #region atributos
        private decimal _idCampo;
        private string _origenCampo;
        private string _nombreCampo;
        private bool? _activo;
        private string _tipoDato;
        private string _nombreCampoRequest;
        private string _nombreCampoPdf;
        private decimal? _ordenPintar;
        private string _formatoCampoPdf;
        private decimal? _idModelo;
        private string _tipoLetra;
        private decimal? _tamanyoLetra;
        private string _colorLetra;
        private string _valorCampoPDF;

        #endregion

        #region propiedades
        /// <summary>
        /// Obtiene/Establece el _idCampo
        /// 
        /// </summary>
        public decimal IdCampo
        {
            get { return this._idCampo; }
            set { this._idCampo = value; }
        }
        
		/// <summary>
        /// Obtiene/Establece el _origenCampo
        /// 
        /// </summary>
        public string OrigenCampo
        {
            get { return this._origenCampo; }
            set { this._origenCampo = value; }
        }
        
		/// <summary>
        /// Obtiene/Establece el _nombreCampo
        /// 
        /// </summary>
        public string NombreCampo
        {
            get { return this._nombreCampo; }
            set { this._nombreCampo = value; }
        }
        
		/// <summary>
        /// Obtiene/Establece el _activo
        /// 
        /// </summary>
        public bool? Activo
        {
            get { return this._activo; }
            set { this._activo = value; }
        }
        
		/// <summary>
        /// Obtiene/Establece el _tipoDato
        /// 
        /// </summary>
        public string TipoDato
        {
            get { return this._tipoDato; }
            set { this._tipoDato = value; }
        }
        
		/// <summary>
        /// Obtiene/Establece el _nombreCampoRequest
        /// 
        /// </summary>
        public string NombreCampoRequest
        {
            get { return this._nombreCampoRequest; }
            set { this._nombreCampoRequest = value; }
        }
        
		/// <summary>
        /// Obtiene/Establece el _nombreCampoPdf
        /// 
        /// </summary>
        public string NombreCampoPdf
        {
            get { return this._nombreCampoPdf; }
            set { this._nombreCampoPdf = value; }
        }
        
		/// <summary>
        /// Obtiene/Establece el _ordenPintar
        /// 
        /// </summary>
        public decimal? OrdenPintar
        {
            get { return this._ordenPintar; }
            set { this._ordenPintar = value; }
        }
        
		/// <summary>
        /// Obtiene/Establece el _formatoCampoPdf
        /// 
        /// </summary>
        public string FormatoCampoPdf
        {
            get { return this._formatoCampoPdf; }
            set { this._formatoCampoPdf = value; }
        }
        
		/// <summary>
        /// Obtiene/Establece el _idModelo
        /// 
        /// </summary>
        public decimal? IdModelo
        {
            get { return this._idModelo; }
            set { this._idModelo = value; }
        }
        
		/// <summary>
        /// Obtiene/Establece el _tipoLetra
        /// 
        /// </summary>
        public string TipoLetra
        {
            get { return this._tipoLetra; }
            set { this._tipoLetra = value; }
        }
        
		/// <summary>
        /// Obtiene/Establece el _tamanyoLetra
        /// 
        /// </summary>
        public decimal? TamanyoLetra
        {
            get { return this._tamanyoLetra; }
            set { this._tamanyoLetra = value; }
        }
        
		/// <summary>
        /// Obtiene/Establece el _colorLetra
        /// 
        /// </summary>
        public string ColorLetra
        {
            get { return this._colorLetra; }
            set { this._colorLetra = value; }
        }

        /// <summary>
        /// Obtiene/Establece el _valorCampoPDF
        /// 
        /// </summary>
        public string ValorCampoPDF
        {
            get { return this._valorCampoPDF; }
            set { this._valorCampoPDF = value; }
        }

        #endregion

    }
}