//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por la herramienta GeneradorCodigo.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto 
//     y se perderán si se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using Iberdrola.Commons.BaseClasses;

namespace Iberdrola.SMG.DAL.DTO
{
    /// <summary>
    /// Atributos y Propiedades de la entidad PMapeoEtiquetasDocumentosConCamposBbdd
    /// </summary>
    public partial class PMapeoEtiquetasDocumentosConCamposBbddDTO
    {
        #region atributos
        private decimal _idCampo;
        private string _nombreProceso;
        private bool? _activo;
        private string _nombreEtiquetaSustituir;
        private string _tablaOrigenCampo;
        private string _nombreCampo;
        private string _tipoDato;
        private string _formatoEtiquetaSustituir;

        #endregion
        
        #region propiedades
		/// <summary>
        /// Obtiene/Establece el _idCampo
        /// 
        /// </summary>
        public decimal IdCampo
        {
            get { return this._idCampo; }
            set { this._idCampo = value; }
        }
        
		/// <summary>
        /// Obtiene/Establece el _nombreProceso
        /// 
        /// </summary>
        public string NombreProceso
        {
            get { return this._nombreProceso; }
            set { this._nombreProceso = value; }
        }
        
		/// <summary>
        /// Obtiene/Establece el _activo
        /// 
        /// </summary>
        public bool? Activo
        {
            get { return this._activo; }
            set { this._activo = value; }
        }
        
		/// <summary>
        /// Obtiene/Establece el _nombreEtiquetaSustituir
        /// 
        /// </summary>
        public string NombreEtiquetaSustituir
        {
            get { return this._nombreEtiquetaSustituir; }
            set { this._nombreEtiquetaSustituir = value; }
        }
        
		/// <summary>
        /// Obtiene/Establece el _tablaOrigenCampo
        /// 
        /// </summary>
        public string TablaOrigenCampo
        {
            get { return this._tablaOrigenCampo; }
            set { this._tablaOrigenCampo = value; }
        }
        
		/// <summary>
        /// Obtiene/Establece el _nombreCampo
        /// 
        /// </summary>
        public string NombreCampo
        {
            get { return this._nombreCampo; }
            set { this._nombreCampo = value; }
        }
        
		/// <summary>
        /// Obtiene/Establece el _tipoDato
        /// 
        /// </summary>
        public string TipoDato
        {
            get { return this._tipoDato; }
            set { this._tipoDato = value; }
        }
        
		/// <summary>
        /// Obtiene/Establece el _formatoEtiquetaSustituir
        /// 
        /// </summary>
        public string FormatoEtiquetaSustituir
        {
            get { return this._formatoEtiquetaSustituir; }
            set { this._formatoEtiquetaSustituir = value; }
        }
        

        #endregion       
        
    }
}