//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por la herramienta GeneradorCodigo.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto 
//     y se perderán si se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using Iberdrola.Commons.BaseClasses;

namespace Iberdrola.SMG.DAL.DTO
{
    /// <summary>
    /// Atributos y Propiedades de la entidad PValidacionesTicketCombustion
    /// </summary>
    public partial class PValidacionesTicketCombustionDTO
    {
        #region atributos
        private decimal _idValidacion;
        private string _tipoPeticion;
        private decimal _idTipoTicket;
        private string _nombreCampo;
        private string _nombreCampoRequest;
        private decimal? _orden;
        private bool? _activo;
        private bool? _obligatorio;
        private string _dependecia;
        private string _valorMinimo;
        private string _valorMaximo;
        private string _anomalia;
        private decimal? _prioridad;

        #endregion

        #region propiedades
        /// <summary>
        /// Obtiene/Establece el _idValidacion
        /// 
        /// </summary>
        public decimal IdValidacion
        {
            get { return this._idValidacion; }
            set { this._idValidacion = value; }
        }
        
		/// <summary>
        /// Obtiene/Establece el _tipoPeticion
        /// 
        /// </summary>
        public string TipoPeticion
        {
            get { return this._tipoPeticion; }
            set { this._tipoPeticion = value; }
        }
        
		/// <summary>
        /// Obtiene/Establece el _idTipoTicket
        /// 
        /// </summary>
        public decimal IdTipoTicket
        {
            get { return this._idTipoTicket; }
            set { this._idTipoTicket = value; }
        }
        
		/// <summary>
        /// Obtiene/Establece el _nombreCampo
        /// 
        /// </summary>
        public string NombreCampo
        {
            get { return this._nombreCampo; }
            set { this._nombreCampo = value; }
        }
        
		/// <summary>
        /// Obtiene/Establece el _nombreCampoRequest
        /// 
        /// </summary>
        public string NombreCampoRequest
        {
            get { return this._nombreCampoRequest; }
            set { this._nombreCampoRequest = value; }
        }
        
		/// <summary>
        /// Obtiene/Establece el _orden
        /// 
        /// </summary>
        public decimal? Orden
        {
            get { return this._orden; }
            set { this._orden = value; }
        }
        
		/// <summary>
        /// Obtiene/Establece el _activo
        /// 
        /// </summary>
        public bool? Activo
        {
            get { return this._activo; }
            set { this._activo = value; }
        }
        
		/// <summary>
        /// Obtiene/Establece el _obligatorio
        /// 
        /// </summary>
        public bool? Obligatorio
        {
            get { return this._obligatorio; }
            set { this._obligatorio = value; }
        }
        
		/// <summary>
        /// Obtiene/Establece el _dependecia
        /// 
        /// </summary>
        public string Dependecia
        {
            get { return this._dependecia; }
            set { this._dependecia = value; }
        }
        
		/// <summary>
        /// Obtiene/Establece el _valorMinimo
        /// 
        /// </summary>
        public string ValorMinimo
        {
            get { return this._valorMinimo; }
            set { this._valorMinimo = value; }
        }
        
		/// <summary>
        /// Obtiene/Establece el _valorMaximo
        /// 
        /// </summary>
        public string ValorMaximo
        {
            get { return this._valorMaximo; }
            set { this._valorMaximo = value; }
        }
        
		/// <summary>
        /// Obtiene/Establece el _anomalia
        /// 
        /// </summary>
        public string Anomalia
        {
            get { return this._anomalia; }
            set { this._anomalia = value; }
        }

        /// <summary>
        /// Obtiene/Establece el _prioridad
        /// 
        /// </summary>
        public decimal? Prioridad
        {
            get { return this._prioridad; }
            set { this._prioridad = value; }
        }

        #endregion

    }
}