//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por la herramienta GeneradorCodigo.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto 
//     y se perderán si se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using Iberdrola.Commons.BaseClasses;

namespace Iberdrola.SMG.DAL.DTO
{
    /// <summary>
    /// Atributos y Propiedades de la entidad PValidacionesTicketCombustion
    /// </summary>
    public partial class PValidacionesTicketCombustionDTO
    {
        #region atributos
      

        #endregion       
        
    }
}