using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

/// <summary>
/// Descripción breve de TextosJavaScript
/// </summary>
public class TextosJavaScript_old
{

    //
    // TODO: Agregar aquí la lógica del constructor
    //
  
private string _ALTA_SOLICITUD = "ALTA SOLICITUD";
private string _CONTRATO_NO_ENCONTRADO = "CONTRATO NO ENCONTRADO (Al cargar datos del cliente)";
private string _MODIF_SOLICITUD = "MODIF. SOLICITUD";
private string _NUMERO_DE_INTENTOS_SUPERADOS = "Ha superado el número de intentos. Se cerrará la ventana.";
private string _SELECCIONE_SUBTIPO_SOLICITUD = "Seleccione subtipo de solicitud...";
private string _SELECCIONE_TIPO_AVERIA = "Seleccione un tipo de averia";
private string _SERVICIO_DADO_DE_BAJA = "EL SERVICIO ESTA DADO DE BAJA";
private string _TEXTO_ACEPTACION_DE_PRESUPUESTO = "Aceptacion de presupuesto";
private string _TEXTO_ADMINISTRACION = "ADMINISTRACION";
private string _TEXTO_ALERTA = "ALERTA";
private string _TEXTO_ALTA_AVERIA_GAS_CONFORT = "VA A DAR DE ALTA UNA SOLICITUD DE AVERIA DE GAS CONFORT ¿DESEA CONTINUAR?";
private string _TEXTO_ALTA_AVERIA_GAS_CONFORT_TITULO = "ALTA AVERIA GAS CONFORT CONTRATO:";
private string _TEXTO_ALTA_GAS_CONFORT = "VA A DAR DE ALTA UNA SOLICITUD DE GAS CONFORT ¿DESEA CONTINUAR?";
private string _TEXTO_ATENCION_AVERIA_ABIERTA = "ATENCIÓN!!!\\nTiene una avería abierta actualmente.";
private string _TEXTO_ATENCION_CONTRATO_BAJA = "ATENCIÓN!!!\\nCONTRATO DADO DE BAJA\\nSolo se permite operar con solicitudes de Visitas o Averias incorrectas.";
private string _TEXTO_ATENCION_CONTRATO_BAJA_POR_RECLAMACION = "ATENCIÓN!!!\\nCONTRATO DADO DE BAJA POR RECLAMACION\\nNo se permite dar de alta solicitudes.";
private string _TEXTO_ATENCION_SOLICITUD_NO_PUEDE_DERIVARSE = "ATENCIÓN!!!\nESTA SOLICITUD NO PUEDE DERIVARSE AL SAT AL SER CALDERA INMERGAS.";
private string _TEXTO_AVERIA = "Averia:";
private string _TEXTO_AVERIA_GAS_CONFORT = "Avería Gas Confort";
private string _TEXTO_AVERIA_INCORRECTA = "Avería incorrecta";
private string _TEXTO_AVERIA_INCORRECTA_GAS_CONFORT = "Avería Incorrecta Gas Confort";
private string _TEXTO_AVERIA_MANTENIMIENTO = "Avería Mantenimiento de Gas";
private string _TEXTO_AVISO = "AVISO";
private string _TEXTO_BAJA_SERVICIO = "Baja servicio";
private string _TEXTO_BUSCAR_USUARIO = "Buscar Usuario";
private string _TEXTO_CALDERAS = "Calderas";
private string _TEXTO_CANCELADA = "Cancelada";
private string _TEXTO_CANCELADA_POR_REASIGNACION = "Cancelada por Reasignacion";
private string _TEXTO_CANCELADA_POR_SISTEMA = "Sistema: Cancelada por sistema";
private string _TEXTO_CANCELADO_TRANSFERIDO_A_SAT = "Cancelado transferido a SAT";
private string _TEXTO_CLIENTE_PREFERENTE_FACEBOOK = "Cliente preferente por queja en facebook:";
private string _TEXTO_CLIENTE_PREFERENTE_TWITTER = "Cliente preferente por queja en twitter:";
private string _TEXTO_COBERTURA_SERVICIO = "COBERTURA SERVICIO ";
private string _TEXTO_CODIFICACION_AVERIAS = "CODIFICACIÓN AVERIAS";
private string _TEXTO_CODIGO_AVERIA_OBLIGATORIO = "El código de averia es obligatorio.";
private string _TEXTO_CODIGO_SOLICITUD = "código solicitud:";
private string _TEXTO_CODIGO_VISITA_OBLIGATORIO = "El código de visita es obligatorio.";
private string _TEXTO_COMPRUEBE_DATOS_BANCARIOS = "Compruebe los datos bancarios.";
private string _TEXTO_COMPRUEBE_DATOS_OBLIGATORIOS = "Compruebe: La recepción del comprobante, El código de barras de la visita, El check de facturado proveedor, La fecha de factura y La caldera seleccionada";
private string _TEXTO_COMPRUEBE_FECHA_INTRODUCIDA = "Compruebe la fecha introducida.";
private string _TEXTO_COMPRUEBE_IMPORTE_INTRODUCIDO = "Compruebe el Importe introducido.";
private string _TEXTO_COMPRUEBE_NUMERO_SERIE_TERMOSTATO = "Compruebe el número de serie del Termostato Inteligente";
private string _TEXTO_CON_CUOTA = " ha pasado a oferta aceptada. Con cuota de: ";
private string _TEXTO_CON_PAGO_FRACCIONADO = "con pago fraccionado";
private string _TEXTO_CONFIRMACION_PASSWORD_NO_VACIA = "La confirmación de la contraseña no puede estar vacía.";
private string _TEXTO_CONTRASENHIA_CARACTERES_ALFANUMERICOS = "0 caractéres no alfanuméricos.";
private string _TEXTO_CONTRASENHIA_CARACTERES_NUMERICOS = "La contraseña tiene que tener al menos los siguientes caracteres numéricos: ";
private string _TEXTO_CONTRASENHIA_DEBE_CUMPLIR = "La nueva contraseña tiene que cumplir las siguientes condiciones:";
private string _TEXTO_CONTRASENHIA_DEBE_TENER = "La contraseña tiene que tener al menos ";
private string _TEXTO_CONTRASENHIA_ENTRE_6Y8 = "Longitud entre 6 y 8 caracteres.";
private string _TEXTO_CONTRASENHIA_INCLUIR_MAYUS_MINUS = "Incluir al menos 1 mayúscula y 1 minúscula.";
private string _TEXTO_CONTRASENHIA_MAYUSCULAS = "caracteres en mayúsculas y";
private string _TEXTO_CONTRASENHIA_MINIMO_2_CARACTERES_NUMERICOS = "Incluir al menos 2 caracteres numéricos.";
private string _TEXTO_CONTRASENHIA_MINUSCULAS = "en minúsculas.";
private string _TEXTO_CONTRASENHIA_MODIFICADA_CORRECTAMENTE = "La contraseña ha sido modificada correctamente.";
private string _TEXTO_CONTRASENHIA_NO_ALPHANUMERICO = "caracteres no alphanumericos como máximo.";
private string _TEXTO_CONTRASENHIA_NO_PUEDE_ESTAR_VACIA = "La contraseña no puede estar vacía.";
private string _TEXTO_CONTRASENHIA_POCO_SEGURA = "Tiene una contraseña poco segura. Por una mayor seguridad establezca una contraseña diferente.";
private string _TEXTO_CONTRASENHIA_TIENE = "La contraseña tiene";
private string _TEXTO_CONTRATO_DADO_DE_BAJA = "Contrato dado de baja";
private string _TEXTO_CONTRATO_MAS_DE_DOS_AVERIAS = "CONTRATO SMG AMPLIADO CON MAS DE DOS AVERIAS RESUELTAS EN EL AÑO. El importe total de las siguientes averías será asumido por el cliente. Avisar al cliente.";
private string _TEXTO_DATOS_ARGUMENTARIO = "DATOS ARGUMENTARIO";
private string _TEXTO_DATOS_CALDERAS_NO_COMPLETOS = "Los datos de la caldera no están completos, no se insertará la caldera.¿Desea continuar?";
private string _TEXTO_DATOS_SOLICITUD = "DATOS DE LA SOLICITUD: ";
private string _TEXTO_DE_SEGUIR_BORRARAN_DATOS_VISITA = "De seguir con el cambio se borraran los datos correspondientes a la vista\n¿Desea continuar?";
private string _TEXTO_DEBE_INIDCAR_PARAMETRO_BUSQUEDA = "Debe de indicar algún parámetro de búsqueda";
private string _TEXTO_DEBE_SELECCIONAR_CONTRATO = "DEBE SELECCIONAR UN CONTRATO";
private string _TEXTO_DEBE_SELECCIONAR_ESTADO_SOLICITUD = "Debe seleccionar un estado de solicitud.";
private string _TEXTO_DEBE_SELECCIONAR_MOTIVO_CANCELACION = "Debe seleccionar un motivo de cancelación.";
private string _TEXTO_DEBE_SELECCIONAR_SUBTIPO = "Debe seleccionar un subtipo de solicitud.";
private string _TEXTO_DEBE_SELECCIONAR_TECNICO = "Debe seleccionar un técnico";
private string _TEXTO_DEBE_SELECCIONAR_TIPO_VISITA = "Debe seleccionar un Tipo de Visita ";
private string _TEXTO_DEL_CONTRATO = " del Contrato: ";
private string _TEXTO_DEMASIADAS_COINCIDENCIAS = "DEMASIADAS COINCIDENCIAS.\\n ACOTE LOS RESULTADOS INFORMANDO MAS FILTROS DE LA BUSQUEDA";
private string _TEXTO_DESCONECTAR = "desconectar";
private string _TEXTO_DESEA_REALMENTE_DAR_BAJA = "¿DESEA REALMENTE DAR DE BAJA EL CONTRATO?";
private string _TEXTO_ELEGIR_ACCION = "ELEGIR ACCIÓN";
private string _TEXTO_ELIMINAR_USUARIO = "Va a eliminar el usuario, ¿Desea Continuar?";
private string _TEXTO_EQUIPAMIENTO = "Equipamiento";
private string _TEXTO_ERROR_AL_OBTENER_DATOS_SOLICITUD_ACTUAL = "Error al obtener datos de la solicitud actual";
private string _TEXTO_ERROR_CARGA_DATOS = "Se ha producido un error en la carga de datos, revise los filtros seleccionados.";
private string _TEXTO_ERROR_MOSTRAR_AVISO = "Error al mostrar el AVISO";
private string _TEXTO_ERROR_VISITA_NO_ENCONTRADA = "No se ha encontrado la visita del contrato. Compruebe el código introducido";
private string _TEXTO_ESTA_SEGURO = "¿ESTA SEGURO? EL CONTRATO DEJARA DE ESTAR OPERATIVO";
private string _TEXTO_EXCEL_DEMASIADAS_FILAS = "No se puede generar el documento Excel con más registros de";
private string _TEXTO_EXCEL_MAS_DE_10000 = "No se puede generar el documento Excel con más de 10000 registros porque tardaría demasiado.";
private string _TEXTO_EXPORTAR_EXCEL = "EXPORTAR EXCEL";
private string _TEXTO_FALTA_FICHERO_OBLIGATORIO = "Falta el fichero obligatorio";
private string _TEXTO_FALTAN_DATOS_OBLIGATORIOS_CALDERA = "Faltan datos obligatorios de la caldera";
private string _TEXTO_FECHA_INTRODUCIDA_NO_PUEDE_SER_MAYOR = "Compruebe la fecha introducida. No puede ser mayor a la fecha de hoy";
private string _TEXTO_FECHA_VISITA_NO_PUEDE_SER_INFERIOR = "La fecha de la visita no puede ser inferior a la fecha limite menos un año.";
private string _TEXTO_FECHA_VISITA_NO_PUEDE_SER_MAYOR = "La fecha de la visita no puede ser mayor que la fecha actual.";
private string _TEXTO_FECHA_VISITA_NO_PUEDE_SER_SUPERIOR = "La fecha de la visita no puede ser superior a la fecha limite.";
private string _TEXTO_FICHERO_EXISTENTE_BBDD = "Fichero ya existente en la BB.DD.";
private string _TEXTO_FILTROS_AVANZADOS = "Filtros Avanzado";
private string _TEXTO_FILTROS_COLUMNA = "Filtros Columna";
private string _TEXTO_FORMATO_NO_AUTORIZADO = "FORMATO NO AUTORIZADO EN ESTE CASO";
private string _TEXTO_GAS_CONFORT = "Gas Confort";
private string _TEXTO_GENERADA_TRAS_LLAMADA_CORTESIA = "Generada tras llamada de cortesía";
private string _TEXTO_INFORMACION_POR_RECLAMACION = "Información por Reclamación";
private string _TEXTO_LA_SOLICITUD = "La Solicitud:";
private string _TEXTO_LISTADO_BERETTA = "Listado Beretta";
private string _TEXTO_LISTADO_CALDERAS = "Listado de Calderas";
private string _TEXTO_LISTADO_MANTENIMIENTOS = "Listado de Mantenimientos";
private string _TEXTO_LISTADO_SOLICITUDES = "Listado de Solicitudes";
private string _TEXTO_MANTENIMIENTO_GAS = "Mantenimiento gas";
private string _TEXTO_MANTENIMIENTO_GAS_CALEFACCION = "Mantenimiento gas calefaccción";
private string _TEXTO_MAS_DE_DOS_AVERIAS = "CONTRATO CON MAS DE 2 AVERIAS RESUELTAS, ¿DESEA CONTINUAR Y CREAR UNA NUEVA? (Tenga en cuenta que el servicio de este contrato solo cubre 2 averias por año)";
private string _TEXTO_MOVIMIENTO_CORRECCION = "MOVIMIENTO DE CORRECCION";
private string _TEXTO_NINGUNO = "Ninguno";
private string _TEXTO_NO = "NO";
private string _TEXTO_NO_ABRIR_AVERIAS_21_DIAS = "No se pueden abrir averias al tener una visita cerrada hace menos de 21 días. \\n EL PROVEEDOR DEBERA DE PONERSE EN CONTACTO CON SU RESPONSABLE.";
private string _TEXTO_NO_ABRIR_AVERIAS_30_DIAS = "No se pueden abrir averias al tener una avería abierta hace menos de 30 días. \\n EL PROVEEDOR DEBERA DE PONERSE EN CONTACTO CON SU RESPONSABLE.";
private string _TEXTO_NO_ALTA_FALTAN_CAMPOS_OBLIGATORIOS = "No se ha dado de alta su solicitud. Todos los campos excepto Observaciones son obligatorios.";
private string _TEXTO_NO_COINCIDEN_LOS_VALORES = "NO COINCIDEN los valores";
private string _TEXTO_NO_DESCHEQUEAR_FACTURADO_PROVEEDOR = "Con número factura informado no se puede deschequear facturado por el proveedor";
private string _TEXTO_NO_EXISTE_SOLICITUDES_EXPORTAR = "No existen solicitudes a exportar";
private string _TEXTO_NO_FACTURAR_VISITA_SI_NO_CERRADA = "No se puede facturar la visita si el estado de esta no es cerrada";
private string _TEXTO_NO_HAY_CODIGO_CONTRATO = "No hay código de contrato";
private string _TEXTO_NO_MODIFICAR_MAS_DE_21_DIAS = "No puede modificar el estado de la visita, debido a que desde la última vez en que modifico el estado de la visita, han pasado mas de 21 dias";
private string _TEXTO_NO_PERMITIDO_INDICAR_REPARACION = "No esta permitido indicar la reparación si la visita no esta cerrada";
private string _TEXTO_NO_SE_HA_PODIDO_ALTA_SOLICITUD = "No se ha podido dar de alta la solicitud. Codigo:";
private string _TEXTO_NO_SE_HA_PODIDO_MODIFICAR_SOLICITUD = "No se ha podido modificar la solicitud. Codigo:";
private string _TEXTO_NO_SE_PERMITE_ENVIO_CARTA = "No se permite seleccionar envio de carta con este estado de la visita";
private string _TEXTO_NOMBREFICHERO_INCORRECTO = "Nombre del fichero incorrecto";
private string _TEXTO_NUEVA_CONTRASENHIA_NP_IGUAL_ACTUAL = "La nueva contraseña no puede ser la misma que la actual.";
private string _TEXTO_NUEVO_AVISO = "Nuevo Aviso";
private string _TEXTO_NUEVO_AVISO_CONTRATO = "Nuevo Aviso - Contrato";
private string _TEXTO_NUEVO_PAGO_ADELANTADO = "Nuevo Pago Adelantado: ";
private string _TEXTO_OCULTAR_HISTORICO = "Ocultar Histórico";
private string _TEXTO_PASSWORD_MINIMO_CARACTERES = "La contraseña debe de tener por lo menos 6 caracteres.";
private string _TEXTO_POR_GARANTIA_TOTAL = "por garantía total";
private string _TEXTO_REPARADA = "reparada";
private string _TEXTO_REPARADA_CON_DOCUMENTACION = "Reparada con documentacion";
private string _TEXTO_REPARADA_POR_TELEFONO = "Reparada por telefono";
private string _TEXTO_REVISION_POR_PRECINTE = "Revisión por Precinte";
private string _TEXTO_SE_DEBEN_RELLENAR_CARACTERISTICAS_OBLIGATORIAS = "Se deben rellenar todas las características Obligatorias.";
private string _TEXTO_SEGUNDA_VEZ_AUSENTE = "Al ser la segunda vez que esta ausente el cliente compruebe los datos obligatorios que tiene que meter. \\n(Fecha de Visita, Recepción del comprobante, Fecha de Factura de la visita y Código de Barras de la visita)";
private string _TEXTO_SELECCIONAR_CONTRATO = "Seleccionar Contrato";
private string _TEXTO_SELECCIONE_MOTIVO_CANCELACION = "Seleccione el motivo de la cancelación";
private string _TEXTO_SELECCIONE_TIPO_VISITA = "Seleccione un tipo de visita";
private string _TEXTO_SERVICIO_MANTENIMIENTO_GAS = "Servicio Mantenimiento Gas";
private string _TEXTO_SERVICIO_MANTENIMIENTO_GAS_CALEFACCION = "Servicio Mantenimiento Gas Calefacción";
private string _TEXTO_SI = "SI";
private string _TEXTO_SOLICITUD_ABIERTA_ACTUALMENTE = "Este contrato tiene una solicitud abierta actualmente.";
private string _TEXTO_SOLICITUD_ALTA = "Se ha dado de alta la solicitud";
private string _TEXTO_SOLICITUD_ALTA_CON_ENVIO_MAIL = "Se ha dado de alta la solicitud,(y se ha enviado un mail al proveedor). Solicitud:";
private string _TEXTO_SOLICITUD_DE_VISITA = "Solicitud de Visita SMG";
private string _TEXTO_SOLICITUD_ELIMINADA = "La solicitud ha sido eliminada.";
private string _TEXTO_SOLICITUD_MODIFICADA = "Se ha modificado la solicitud";
private string _TEXTO_SOLICITUD_MODIFICADA_CON_ENVIO_MAIL = "Se ha modificado la solicitud,(y se ha enviado un mail al proveedor). Solicitud:";
private string _TEXTO_SOLICITUD_NO_MODIFICADA = "No se ha podido modificar la solicitud.";
private string _TEXTO_SOLICITUD_NO_RESUELTA_LLAMADA_CORTESIA = "Solicitud de avería no resuelta tras llamada de cortesía";
private string _TEXTO_SOLICITUD_RECLAMACION = "Solicitud Reclamacion";
private string _TEXTO_SOLICITUDES = "solicitudes";
private string _TEXTO_TAMANIO_FICHERO_INCORRECTO = "Tamaño del fichero incorrecto";
private string _TEXTO_TECNICO_SUPERA_LIMITE_VISITAS_DIA = "Este técnico ha alcanzado el límite de 15 visitas/día . ";
private string _TEXTO_TELEFONO_DEBE_COMENZAR_6789 = "El telefono debe de comenzar por el digito 6, 7, 9 o 8";
private string _TEXTO_TELEFONO_DEBE_TENER_9_DIGITOS = "El telefono debe de tener 9 dígitos";
private string _TEXTO_TELEFONO_OBLIGATORIO = "El telefono es obligatorio";
private string _TEXTO_TELEFONOS_ACTUALIZADOS = "Telefonos Actualizados";
private string _TEXTO_TODAS = "TODAS";
private string _TEXTO_TODOS = "TODOS";
private string _TEXTO_VALORACION_CUADRO_MANDO = "VALORACION CUADRO MANDO";
private string _TEXTO_VER_HISTORICO = "Ver Histórico";
private string _TEXTO_VISITA = "Visita:";
private string _TEXTO_VISITA_MODIFICAR_FACTURADA = "La visita que va a modificar esta Facturada. Si no le quita el numero de factura, no podra modificarla, aunque cambie el estado.";
private string _TEXTO_VISITA_REALIZADA = "Visita Realizada";
private string _TEXTO_VISITA_SUPERVISION = "Visita supervision";
private string _TEXTO_VUELVA_A_SELECCIONAR_LA_SOLICITUD = "Vuelva a seleccionar la solicitud en la búsqueda";
private string _TEXTO_YA_LIQUIDADO_CAMBIAR_ESTADO = "¿SOLICITUD/VISITA YA LIQUIDADA, QUIERE CAMBIAR EL ESTADO?";
private string _TEXTO_YA_LIQUIDADO_ELIMINAR = "¿SOLICITUD YA LIQUIDADA, ESTA SEGURO QUE QUIERE ELIMINARLA?";
private string _TEXZTO_CONTRASENHIA_CADUCADA = "La contraseña actual ha caducado.";
private string _HORARIOProveedor = "Horario Proveedor: De lunes a viernes de 8h a 20h. Sábados de 9h a 14h";


//*******************************************
//PORTUGAL
//*******************************************
private string _ALTA_SOLICITUD_PT = "PEDIDO DE ADESÃO";
private string _CONTRATO_NO_ENCONTRADO_PT = "CONTRATO Não foi encontrada ( Ao carregar os dados dos clientes )";
private string _MODIF_SOLICITUD_PT = "MODIF. PEDIDO";
private string _NUMERO_DE_INTENTOS_SUPERADOS_PT = "Você excedeu o número de tentativas . a janela será fechada.";
private string _SELECCIONE_SUBTIPO_SOLICITUD_PT = "Seleções subtipo de pedido...";
private string _SELECCIONE_TIPO_AVERIA_PT = "Selecione um tipo de avaria";
private string _SERVICIO_DADO_DE_BAJA_PT = "O SERVIÇO FOI CANCELADO";
private string _TEXTO_ACEPTACION_DE_PRESUPUESTO_PT = "Aceitação de orçamento";
private string _TEXTO_ADMINISTRACION_PT = "ADMINISTRAÇÃO";
private string _TEXTO_ALERTA_PT = "ALERTA";
private string _TEXTO_ALTA_AVERIA_GAS_CONFORT_PT = "VAI INSCREVER UM PEDIDO DE AVARIA DE GÁS CONFORTO. PRETENDE CONTINUAR?";
private string _TEXTO_ALTA_AVERIA_GAS_CONFORT_TITULO_PT = "ALTA AVARIA DE GÁS CONFORTO CONTRATO:";
private string _TEXTO_ALTA_GAS_CONFORT_PT = "VAI INSCREVER UM PEDIDO DE GÁS CONFORTO. PRETENDE CONTINUAR?";
private string _TEXTO_ATENCION_AVERIA_ABIERTA_PT = "ATENÇÃO!!! Tem uma avaria aberta atualmente.";
private string _TEXTO_ATENCION_CONTRATO_BAJA_PT = "ATENÇÃO!!! CONTRATO CANCELADO. Só tem autorização para operar com pedidos de Visitas ou Avarias incorretas.";
private string _TEXTO_ATENCION_CONTRATO_BAJA_POR_RECLAMACION_PT = "ATENÇÃO!!! CONTRATO CANCELADO POR RECLAMAÇÃO. Não é permitido realizar pedidos.";
private string _TEXTO_ATENCION_SOLICITUD_NO_PUEDE_DERIVARSE_PT = "ATENÇÃO!!! ESTE PEDIDO NÃO PODE SER DERIVADO PARA O SATÉLITE AO SER CALDEIRA INMERGAS.";
private string _TEXTO_AVERIA_PT = "Avaria:";
private string _TEXTO_AVERIA_GAS_CONFORT_PT = "Avaria de gás conforto";
private string _TEXTO_AVERIA_INCORRECTA_PT = "Avaria incorreta";
private string _TEXTO_AVERIA_INCORRECTA_GAS_CONFORT_PT = "Avaria incorreta de gás conforto";
private string _TEXTO_AVERIA_MANTENIMIENTO_PT = "Avaria manutenção de gás";
private string _TEXTO_AVISO_PT = "AVISO ";
private string _TEXTO_BAJA_SERVICIO_PT = "Cancelamento do serviço";
private string _TEXTO_BUSCAR_USUARIO_PT = "Procurar utilizador";
private string _TEXTO_CALDERAS_PT = "Caldeiras";
private string _TEXTO_CANCELADA_PT = "Cancelada ";
private string _TEXTO_CANCELADA_POR_REASIGNACION_PT = "Cancelado por reatribuição";
private string _TEXTO_CANCELADA_POR_SISTEMA_PT = "Sistema: Cancelado pelo sistema";
private string _TEXTO_CANCELADO_TRANSFERIDO_A_SAT_PT = "Cancelado transferido para SAT";
private string _TEXTO_CLIENTE_PREFERENTE_FACEBOOK_PT = "Cliente preferente por queija no Facebook:";
private string _TEXTO_CLIENTE_PREFERENTE_TWITTER_PT = "Cliente preferente por queija no Twitter:";
private string _TEXTO_COBERTURA_SERVICIO_PT = "COBERTURA SERVIÇO";
private string _TEXTO_CODIFICACION_AVERIAS_PT = "CODIFICAÇÃO DE AVARIAS";
private string _TEXTO_CODIGO_AVERIA_OBLIGATORIO_PT = "O código de falha é necessária.";
private string _TEXTO_CODIGO_SOLICITUD_PT = "código solicitud: PT ";
private string _TEXTO_CODIGO_VISITA_OBLIGATORIO_PT = "O código de avaria é obrigatório.";
private string _TEXTO_COMPRUEBE_DATOS_BANCARIOS_PT = "Verifique os dados bancários.";
private string _TEXTO_COMPRUEBE_DATOS_OBLIGATORIOS_PT = "Verifique: A receção do comprovativo, o código de barras da visita, a verificação de faturação do fornecedor, a data de fatura e a caldeira selecionada";
private string _TEXTO_COMPRUEBE_FECHA_INTRODUCIDA_PT = "Comprove a data introduzida.";
private string _TEXTO_COMPRUEBE_IMPORTE_INTRODUCIDO_PT = "Comprove o montante introduzido.";
private string _TEXTO_COMPRUEBE_NUMERO_SERIE_TERMOSTATO_PT = "Verifique o número de série do Termóstato Inteligente.";
private string _TEXTO_CON_CUOTA_PT = " passou a oferta aceite. Com quota de:";
private string _TEXTO_CON_PAGO_FRACCIONADO_PT = " com pagamento fracionado";
private string _TEXTO_CONFIRMACION_PASSWORD_NO_VACIA_PT = "A confirmação da palavra-chave não pode estar vazia.";
private string _TEXTO_CONTRASENHIA_CARACTERES_ALFANUMERICOS_PT = "0 caracteres não alfanuméricos.";
private string _TEXTO_CONTRASENHIA_CARACTERES_NUMERICOS_PT = "A palavra-chave tem de ter pelo menos os seguintes caracteres numéricos:";
private string _TEXTO_CONTRASENHIA_DEBE_CUMPLIR_PT = "A nova palavra-chave tem de cumprir as seguintes condições:";
private string _TEXTO_CONTRASENHIA_DEBE_TENER_PT = "A palavra-chave tem de ter pelo menos";
private string _TEXTO_CONTRASENHIA_ENTRE_6Y8_PT = "Longitude entre 6 e 8 caracteres.";
private string _TEXTO_CONTRASENHIA_INCLUIR_MAYUS_MINUS_PT = "Incluir pelo menos 1 maiúscula e 1 minúscula.";
private string _TEXTO_CONTRASENHIA_MAYUSCULAS_PT = "caracteres em maiúsculas e ";
private string _TEXTO_CONTRASENHIA_MINIMO_2_CARACTERES_NUMERICOS_PT = "Incluir pelo menos 2 caracteres numéricos.";
private string _TEXTO_CONTRASENHIA_MINUSCULAS_PT = "em minúsculas.";
private string _TEXTO_CONTRASENHIA_MODIFICADA_CORRECTAMENTE_PT = "A palavra-chave foi modificada corretamente.";
private string _TEXTO_CONTRASENHIA_NO_ALPHANUMERICO_PT = "caracteres não alfanuméricos como máximo.";
private string _TEXTO_CONTRASENHIA_NO_PUEDE_ESTAR_VACIA_PT = "A palavra-chave não pode estar vazia.";
private string _TEXTO_CONTRASENHIA_POCO_SEGURA_PT = "Tem uma palavra-chave pouco segura. Para maior segurança estabeleça uma palavra-chave diferente.";
private string _TEXTO_CONTRASENHIA_TIENE_PT = "A palavra-chave tem";
private string _TEXTO_CONTRATO_DADO_DE_BAJA_PT = "Contrato cancelado";
private string _TEXTO_CONTRATO_MAS_DE_DOS_AVERIAS_PT = "CONTRATO SMG AMPLIADO COM MAIS DE DUAS AVARIAS RESOLVIDAS NO ANO. O montante total das seguintes avarias será assumido pelo cliente. Avisar o cliente.";
private string _TEXTO_DATOS_ARGUMENTARIO_PT = "DADOS DO ARGUMENTÁRIO";
private string _TEXTO_DATOS_CALDERAS_NO_COMPLETOS_PT = "Os dados da caldeira não estão completos, a caldeira não será inserida. Pretende continuar?";
private string _TEXTO_DATOS_SOLICITUD_PT = "DADOS DO PEDIDO: ";
private string _TEXTO_DE_SEGUIR_BORRARAN_DATOS_VISITA_PT = "Se prosseguir com a alteração serão alterados os dados correspondentes à vista. Deseja continuar?";
private string _TEXTO_DEBE_INIDCAR_PARAMETRO_BUSQUEDA_PT = "Deve indicar algum parâmetro de pesquisa";
private string _TEXTO_DEBE_SELECCIONAR_CONTRATO_PT = "DEVE SELECIONAR UM CONTRATO";
private string _TEXTO_DEBE_SELECCIONAR_ESTADO_SOLICITUD_PT = "Deve selecionar um estado de pedido.";
private string _TEXTO_DEBE_SELECCIONAR_MOTIVO_CANCELACION_PT = "Deve selecionar um motivo do cancelamento.";
private string _TEXTO_DEBE_SELECCIONAR_SUBTIPO_PT = "Deve selecionar um subtipo de pedido.";
private string _TEXTO_DEBE_SELECCIONAR_TECNICO_PT = "Deve selecionar um técnico";
private string _TEXTO_DEBE_SELECCIONAR_TIPO_VISITA_PT = "Deve selecionar um Tipo de Visita";
private string _TEXTO_DEL_CONTRATO_PT = " do Contrato: ";
private string _TEXTO_DEMASIADAS_COINCIDENCIAS_PT = "DEMASIADAS COINCIDÊNCIAS. LIMITE OS RESULTADOS INFORMANDO SOBRE MAIS FILTROS DA PESQUISA";
private string _TEXTO_DESCONECTAR_PT = "desligar";
private string _TEXTO_DESEA_REALMENTE_DAR_BAJA_PT = "PRETENDE REALMENTE CANCELAR O CONTRATO?";
private string _TEXTO_ELEGIR_ACCION_PT = "ESCOLHER AÇÃO";
private string _TEXTO_ELIMINAR_USUARIO_PT = "Vai eliminar o utilizador. Pretende continuar?";
private string _TEXTO_EQUIPAMIENTO_PT = "Equipamento";
private string _TEXTO_ERROR_AL_OBTENER_DATOS_SOLICITUD_ACTUAL_PT = "Erro ao obter dados do pedido atual";
private string _TEXTO_ERROR_CARGA_DATOS_PT = "Houve um erro no carregamento de dados, verificar os filtros.";
private string _TEXTO_ERROR_MOSTRAR_AVISO_PT = "Erro ao mostrar o AVISO";
private string _TEXTO_ERROR_VISITA_NO_ENCONTRADA_PT = "Não encontrou a visita do contrato. Verifique o código introduzido.";
private string _TEXTO_ESTA_SEGURO_PT = "TEM A CERTEZA? O CONTRATO VAI DEIXAR DE ESTAR OPERACIONAL";
private string _TEXTO_EXCEL_DEMASIADAS_FILAS_PT = "Não é possível criar o documento Excel com mais registos de";
private string _TEXTO_EXCEL_MAS_DE_10000_PT = "Não é possível criar o documento Excel com mais de 10000 registos porque iria demorar demasiado tempo.";
private string _TEXTO_EXPORTAR_EXCEL_PT = "EXPORTAR EXCEL";
private string _TEXTO_FALTA_FICHERO_OBLIGATORIO_PT = "Faltando arquivo necessário";
private string _TEXTO_FALTAN_DATOS_OBLIGATORIOS_CALDERA_PT = "Faltam dados obrigatórios da caldeira";
private string _TEXTO_FECHA_INTRODUCIDA_NO_PUEDE_SER_MAYOR_PT = "Comprove a data introduzida. Não poder ser posterior à data de hoje. ";
private string _TEXTO_FECHA_VISITA_NO_PUEDE_SER_INFERIOR_PT = "A data da visita não pode ser menos do que o prazo menos um ano.";
private string _TEXTO_FECHA_VISITA_NO_PUEDE_SER_MAYOR_PT = "A data da visita não pode ser maior que a data atual.";
private string _TEXTO_FECHA_VISITA_NO_PUEDE_SER_SUPERIOR_PT = "A data da visita não pode exceder o prazo.";
private string _TEXTO_FICHERO_EXISTENTE_BBDD_PT = "Ficheiro já existente na B.D. ";
private string _TEXTO_FILTROS_AVANZADOS_PT = "Filtros avançado";
private string _TEXTO_FILTROS_COLUMNA_PT = "Filtros Columna";
private string _TEXTO_FORMATO_NO_AUTORIZADO_PT = "FORMATO NÃO AUTORIZADO NESTE CASO";
private string _TEXTO_GAS_CONFORT_PT = "Gás Conforto";
private string _TEXTO_GENERADA_TRAS_LLAMADA_CORTESIA_PT = "Criada após chamada de cortesia";
private string _TEXTO_INFORMACION_POR_RECLAMACION_PT = "Informação por reclamação";
private string _TEXTO_LA_SOLICITUD_PT = "O pedido: ";
private string _TEXTO_LISTADO_BERETTA_PT = "Listagem Beretta";
private string _TEXTO_LISTADO_CALDERAS_PT = "Listagem de caldeiras";
private string _TEXTO_LISTADO_MANTENIMIENTOS_PT = "Listagem de manutenções";
private string _TEXTO_LISTADO_SOLICITUDES_PT = "Listagem de Pedidos";
private string _TEXTO_MANTENIMIENTO_GAS_PT = "Manutenção de gás";
private string _TEXTO_MANTENIMIENTO_GAS_CALEFACCION_PT = "Manutenção de gás de aquecimento";
private string _TEXTO_MAS_DE_DOS_AVERIAS_PT = "CONTRATO COM MAIS DE 2 AVARIAS SOLUCIONADAS. PRETENDE CONTINUAR E CRIAR UMA NOVA? (Ter em conta que o serviço deste contrato só abarca 2 avarias por ano)";
private string _TEXTO_MOVIMIENTO_CORRECCION_PT = "MOVIMENTO Correção";
private string _TEXTO_NINGUNO_PT = "Nenhum";
private string _TEXTO_NO_PT = "NÃO";
private string _TEXTO_NO_ABRIR_AVERIAS_21_DIAS_PT = "Não é possível abrir avarias ao ter uma visita fechada há menos de 21 dias. O FORNECEDOR DEVERÁ ENTRAR EM CONTACTO COM O SEU RESPONSÁVEL.";
private string _TEXTO_NO_ABRIR_AVERIAS_30_DIAS_PT = "Não se podem abrir avarias ao ter uma avaria aberta há menos de 30 dias. O FORNECEDOR DEVERÁ ENTRAR EM CONTACTO COM O SEU RESPONSÁVEL.";
private string _TEXTO_NO_ALTA_FALTAN_CAMPOS_OBLIGATORIOS_PT = "O seu pedido não foi inscrito. Todos os campos exceto 'Observações' são obrigatórios.";
private string _TEXTO_NO_COINCIDEN_LOS_VALORES_PT = "Os valores NÃO COINCIDEM";
private string _TEXTO_NO_DESCHEQUEAR_FACTURADO_PROVEEDOR_PT = "Com o número de fatura informado não é possível retirar verificação de faturado pelo fornecedor";
private string _TEXTO_NO_EXISTE_SOLICITUDES_EXPORTAR_PT = "Não existem pedidos a exportar";
private string _TEXTO_NO_FACTURAR_VISITA_SI_NO_CERRADA_PT = "Não é possível faturar a visita se o estado da mesma não for fechado";
private string _TEXTO_NO_HAY_CODIGO_CONTRATO_PT = "Não há código de contrato";
private string _TEXTO_NO_MODIFICAR_MAS_DE_21_DIAS_PT = "Não pode alterar o estado da visita porque desde a última vez que modificou o estado da visita passaram mais de 21 dias";
private string _TEXTO_NO_PERMITIDO_INDICAR_REPARACION_PT = "Não é permitido indicar a reparação se a visita não estiver fechada";
private string _TEXTO_NO_SE_HA_PODIDO_ALTA_SOLICITUD_PT = "Não foi possível inscrever o pedido. Código:";
private string _TEXTO_NO_SE_HA_PODIDO_MODIFICAR_SOLICITUD_PT = "Não foi possível modificar o pedido. Código:";
private string _TEXTO_NO_SE_PERMITE_ENVIO_CARTA_PT = "Não é permitido selecionar envio de carta com este estado da visita";
private string _TEXTO_NOMBREFICHERO_INCORRECTO_PT = "Nome do ficheiro incorreto";
private string _TEXTO_NUEVA_CONTRASENHIA_NP_IGUAL_ACTUAL_PT = "A nova palavra-chave não pode ser a mesma que a atual.";
private string _TEXTO_NUEVO_AVISO_PT = "Novo Aviso";
private string _TEXTO_NUEVO_AVISO_CONTRATO_PT = "Novo Aviso - Contrato";
private string _TEXTO_NUEVO_PAGO_ADELANTADO_PT = "Novo pagamento adiantado:";
private string _TEXTO_OCULTAR_HISTORICO_PT = "Ocultar Histórico";
private string _TEXTO_PASSWORD_MINIMO_CARACTERES_PT = "A palavra-chave deve ter pelo menos 6 caracteres.";
private string _TEXTO_POR_GARANTIA_TOTAL_PT = " por garantia total";
private string _TEXTO_REPARADA_PT = "reparada";
private string _TEXTO_REPARADA_CON_DOCUMENTACION_PT = "Reparada com documentação";
private string _TEXTO_REPARADA_POR_TELEFONO_PT = "Reparada por telefone";
private string _TEXTO_REVISION_POR_PRECINTE_PT = "Revisão por selagem";
private string _TEXTO_SE_DEBEN_RELLENAR_CARACTERISTICAS_OBLIGATORIAS_PT = "Devem ser preenchidas todas as características obrigatórias.";
private string _TEXTO_SEGUNDA_VEZ_AUSENTE_PT = "Ao ser a segunda vez que está ausente, o cliente deve comprovar os dados obrigatórios que tem de preencher. (Data de visita, receção do comprovativo, data de fatura da visita e código de barras da visita)";
private string _TEXTO_SELECCIONAR_CONTRATO_PT = "Selecionar Contrato ";
private string _TEXTO_SELECCIONE_MOTIVO_CANCELACION_PT = "Selecione o motivo do cancelamento";
private string _TEXTO_SELECCIONE_TIPO_VISITA_PT = "Selecione um tipo de visita";
private string _TEXTO_SERVICIO_MANTENIMIENTO_GAS_PT = "Serviço de manutenção gás ";
private string _TEXTO_SERVICIO_MANTENIMIENTO_GAS_CALEFACCION_PT = "Serviço de manutenção gás aquecimento";
private string _TEXTO_SI_PT = "Se";
private string _TEXTO_SOLICITUD_ABIERTA_ACTUALMENTE_PT = "Este contrato tem um pedido aberto atualmente.";
private string _TEXTO_SOLICITUD_ALTA_PT = "O pedido foi inscrito ";
private string _TEXTO_SOLICITUD_ALTA_CON_ENVIO_MAIL_PT = "O pedido foi inscrito (e foi enviado um correio eletrónico ao fornecedor). ";
private string _TEXTO_SOLICITUD_DE_VISITA_PT = "Pedido de visita SMG";
private string _TEXTO_SOLICITUD_ELIMINADA_PT = "O pedido foi eliminado.";
private string _TEXTO_SOLICITUD_MODIFICADA_PT = "O pedido foi alterado";
private string _TEXTO_SOLICITUD_MODIFICADA_CON_ENVIO_MAIL_PT = "Foi alterado o pedido (e foi enviado um correio eletrónico ao fornecedor). Pedido:";
private string _TEXTO_SOLICITUD_NO_MODIFICADA_PT = "Não foi possível modificar o pedido. ";
private string _TEXTO_SOLICITUD_NO_RESUELTA_LLAMADA_CORTESIA_PT = "Pedido de avaria não resolvida após chamada de cortesia";
private string _TEXTO_SOLICITUD_RECLAMACION_PT = "Pedido reclamação ";
private string _TEXTO_SOLICITUDES_PT = "pedido";
private string _TEXTO_TAMANIO_FICHERO_INCORRECTO_PT = "Tamanho do ficheiro incorreto";
private string _TEXTO_TECNICO_SUPERA_LIMITE_VISITAS_DIA_PT = "Este técnico alcançou o limite de 15 visitas/dia.";
private string _TEXTO_TELEFONO_DEBE_COMENZAR_6789_PT = "O telefone deve começar pelo dígito 6, 7, 9 ou 8";
private string _TEXTO_TELEFONO_DEBE_TENER_9_DIGITOS_PT = "O telefone deve ter 9 dígitos";
private string _TEXTO_TELEFONO_OBLIGATORIO_PT = "O telefone é obrigatório";
private string _TEXTO_TELEFONOS_ACTUALIZADOS_PT = "Telefones atualizados";
private string _TEXTO_TODAS_PT = "TODAS";
private string _TEXTO_TODOS_PT = "TODOS";
private string _TEXTO_VALORACION_CUADRO_MANDO_PT = "AVALIAÇÃO DE PAINEL DE CONTROLO";
private string _TEXTO_VER_HISTORICO_PT = "Ver Histórico";
private string _TEXTO_VISITA_PT = "Visita:";
private string _TEXTO_VISITA_MODIFICAR_FACTURADA_PT = "A visita que vai modificar está Faturada. Se não retirar o número de fatura, não a poderá modificar, embora altere o estado.";
private string _TEXTO_VISITA_REALIZADA_PT = "Visita realizada";
private string _TEXTO_VISITA_SUPERVISION_PT = "Visita supervisão";
private string _TEXTO_VUELVA_A_SELECCIONAR_LA_SOLICITUD_PT = "Selecione novamente o pedido de pesquisa";
private string _TEXTO_YA_LIQUIDADO_CAMBIAR_ESTADO_PT = "PEDIDO/VISITA JÁ LIQUIDADO. PRETENDE ALTERAR O ESTADO?";
private string _TEXTO_YA_LIQUIDADO_ELIMINAR_PT = "PEDIDO/VISITA JÁ LIQUIDADO. PRETENDE REALMENTE ELIMINAR?";
private string _TEXZTO_CONTRASENHIA_CADUCADA_PT = "A palavra-chave atual caducou.";
private string _HORARIOProveedor_PT = "Cronograma Fornececedor: De segunda a sexta de 8h a 20h. Sábados de 9h a 14h";


public string ALTA_SOLICITUD { get { return _ALTA_SOLICITUD; } set { _ALTA_SOLICITUD = value; } }
public string CONTRATO_NO_ENCONTRADO { get { return _CONTRATO_NO_ENCONTRADO; } set { _CONTRATO_NO_ENCONTRADO = value; } }
public string MODIF_SOLICITUD { get { return _MODIF_SOLICITUD; } set { _MODIF_SOLICITUD = value; } }
public string NUMERO_DE_INTENTOS_SUPERADOS { get { return _NUMERO_DE_INTENTOS_SUPERADOS; } set { _NUMERO_DE_INTENTOS_SUPERADOS = value; } }
public string SELECCIONE_SUBTIPO_SOLICITUD { get { return _SELECCIONE_SUBTIPO_SOLICITUD; } set { _SELECCIONE_SUBTIPO_SOLICITUD = value; } }
public string SELECCIONE_TIPO_AVERIA { get { return _SELECCIONE_TIPO_AVERIA; } set { _SELECCIONE_TIPO_AVERIA = value; } }
public string SERVICIO_DADO_DE_BAJA { get { return _SERVICIO_DADO_DE_BAJA; } set { _SERVICIO_DADO_DE_BAJA = value; } }
public string TEXTO_ACEPTACION_DE_PRESUPUESTO { get { return _TEXTO_ACEPTACION_DE_PRESUPUESTO; } set { _TEXTO_ACEPTACION_DE_PRESUPUESTO = value; } }
public string TEXTO_ADMINISTRACION { get { return _TEXTO_ADMINISTRACION; } set { _TEXTO_ADMINISTRACION = value; } }
public string TEXTO_ALERTA { get { return _TEXTO_ALERTA; } set { _TEXTO_ALERTA = value; } }
public string TEXTO_ALTA_AVERIA_GAS_CONFORT { get { return _TEXTO_ALTA_AVERIA_GAS_CONFORT; } set { _TEXTO_ALTA_AVERIA_GAS_CONFORT = value; } }
public string TEXTO_ALTA_AVERIA_GAS_CONFORT_TITULO { get { return _TEXTO_ALTA_AVERIA_GAS_CONFORT_TITULO; } set { _TEXTO_ALTA_AVERIA_GAS_CONFORT_TITULO = value; } }
public string TEXTO_ALTA_GAS_CONFORT { get { return _TEXTO_ALTA_GAS_CONFORT; } set { _TEXTO_ALTA_GAS_CONFORT = value; } }
public string TEXTO_ATENCION_AVERIA_ABIERTA { get { return _TEXTO_ATENCION_AVERIA_ABIERTA; } set { _TEXTO_ATENCION_AVERIA_ABIERTA = value; } }
public string TEXTO_ATENCION_CONTRATO_BAJA { get { return _TEXTO_ATENCION_CONTRATO_BAJA; } set { _TEXTO_ATENCION_CONTRATO_BAJA = value; } }
public string TEXTO_ATENCION_CONTRATO_BAJA_POR_RECLAMACION { get { return _TEXTO_ATENCION_CONTRATO_BAJA_POR_RECLAMACION; } set { _TEXTO_ATENCION_CONTRATO_BAJA_POR_RECLAMACION = value; } }
public string TEXTO_ATENCION_SOLICITUD_NO_PUEDE_DERIVARSE { get { return _TEXTO_ATENCION_SOLICITUD_NO_PUEDE_DERIVARSE; } set { _TEXTO_ATENCION_SOLICITUD_NO_PUEDE_DERIVARSE = value; } }
public string TEXTO_AVERIA { get { return _TEXTO_AVERIA; } set { _TEXTO_AVERIA = value; } }
public string TEXTO_AVERIA_GAS_CONFORT { get { return _TEXTO_AVERIA_GAS_CONFORT; } set { _TEXTO_AVERIA_GAS_CONFORT = value; } }
public string TEXTO_AVERIA_INCORRECTA { get { return _TEXTO_AVERIA_INCORRECTA; } set { _TEXTO_AVERIA_INCORRECTA = value; } }
public string TEXTO_AVERIA_INCORRECTA_GAS_CONFORT { get { return _TEXTO_AVERIA_INCORRECTA_GAS_CONFORT; } set { _TEXTO_AVERIA_INCORRECTA_GAS_CONFORT = value; } }
public string TEXTO_AVERIA_MANTENIMIENTO { get { return _TEXTO_AVERIA_MANTENIMIENTO; } set { _TEXTO_AVERIA_MANTENIMIENTO = value; } }
public string TEXTO_AVISO { get { return _TEXTO_AVISO; } set { _TEXTO_AVISO = value; } }
public string TEXTO_BAJA_SERVICIO { get { return _TEXTO_BAJA_SERVICIO; } set { _TEXTO_BAJA_SERVICIO = value; } }
public string TEXTO_BUSCAR_USUARIO { get { return _TEXTO_BUSCAR_USUARIO; } set { _TEXTO_BUSCAR_USUARIO = value; } }
public string TEXTO_CALDERAS { get { return _TEXTO_CALDERAS; } set { _TEXTO_CALDERAS = value; } }
public string TEXTO_CANCELADA { get { return _TEXTO_CANCELADA; } set { _TEXTO_CANCELADA = value; } }
public string TEXTO_CANCELADA_POR_REASIGNACION { get { return _TEXTO_CANCELADA_POR_REASIGNACION; } set { _TEXTO_CANCELADA_POR_REASIGNACION = value; } }
public string TEXTO_CANCELADA_POR_SISTEMA { get { return _TEXTO_CANCELADA_POR_SISTEMA; } set { _TEXTO_CANCELADA_POR_SISTEMA = value; } }
public string TEXTO_CANCELADO_TRANSFERIDO_A_SAT { get { return _TEXTO_CANCELADO_TRANSFERIDO_A_SAT; } set { _TEXTO_CANCELADO_TRANSFERIDO_A_SAT = value; } }
public string TEXTO_CLIENTE_PREFERENTE_FACEBOOK { get { return _TEXTO_CLIENTE_PREFERENTE_FACEBOOK; } set { _TEXTO_CLIENTE_PREFERENTE_FACEBOOK = value; } }
public string TEXTO_CLIENTE_PREFERENTE_TWITTER { get { return _TEXTO_CLIENTE_PREFERENTE_TWITTER; } set { _TEXTO_CLIENTE_PREFERENTE_TWITTER = value; } }
public string TEXTO_COBERTURA_SERVICIO { get { return _TEXTO_COBERTURA_SERVICIO; } set { _TEXTO_COBERTURA_SERVICIO = value; } }
public string TEXTO_CODIFICACION_AVERIAS { get { return _TEXTO_CODIFICACION_AVERIAS; } set { _TEXTO_CODIFICACION_AVERIAS = value; } }
public string TEXTO_CODIGO_AVERIA_OBLIGATORIO { get { return _TEXTO_CODIGO_AVERIA_OBLIGATORIO; } set { _TEXTO_CODIGO_AVERIA_OBLIGATORIO = value; } }
public string TEXTO_CODIGO_SOLICITUD { get { return _TEXTO_CODIGO_SOLICITUD; } set { _TEXTO_CODIGO_SOLICITUD = value; } }
public string TEXTO_CODIGO_VISITA_OBLIGATORIO { get { return _TEXTO_CODIGO_VISITA_OBLIGATORIO; } set { _TEXTO_CODIGO_VISITA_OBLIGATORIO = value; } }
public string TEXTO_COMPRUEBE_DATOS_BANCARIOS { get { return _TEXTO_COMPRUEBE_DATOS_BANCARIOS; } set { _TEXTO_COMPRUEBE_DATOS_BANCARIOS = value; } }
public string TEXTO_COMPRUEBE_DATOS_OBLIGATORIOS { get { return _TEXTO_COMPRUEBE_DATOS_OBLIGATORIOS; } set { _TEXTO_COMPRUEBE_DATOS_OBLIGATORIOS = value; } }
public string TEXTO_COMPRUEBE_FECHA_INTRODUCIDA { get { return _TEXTO_COMPRUEBE_FECHA_INTRODUCIDA; } set { _TEXTO_COMPRUEBE_FECHA_INTRODUCIDA = value; } }
public string TEXTO_COMPRUEBE_IMPORTE_INTRODUCIDO { get { return _TEXTO_COMPRUEBE_IMPORTE_INTRODUCIDO; } set { _TEXTO_COMPRUEBE_IMPORTE_INTRODUCIDO = value; } }
public string TEXTO_COMPRUEBE_NUMERO_SERIE_TERMOSTATO { get { return _TEXTO_COMPRUEBE_NUMERO_SERIE_TERMOSTATO; } set { _TEXTO_COMPRUEBE_NUMERO_SERIE_TERMOSTATO = value; } }
public string TEXTO_CON_CUOTA { get { return _TEXTO_CON_CUOTA; } set { _TEXTO_CON_CUOTA = value; } }
public string TEXTO_CON_PAGO_FRACCIONADO { get { return _TEXTO_CON_PAGO_FRACCIONADO; } set { _TEXTO_CON_PAGO_FRACCIONADO = value; } }
public string TEXTO_CONFIRMACION_PASSWORD_NO_VACIA { get { return _TEXTO_CONFIRMACION_PASSWORD_NO_VACIA; } set { _TEXTO_CONFIRMACION_PASSWORD_NO_VACIA = value; } }
public string TEXTO_CONTRASENHIA_CARACTERES_ALFANUMERICOS { get { return _TEXTO_CONTRASENHIA_CARACTERES_ALFANUMERICOS; } set { _TEXTO_CONTRASENHIA_CARACTERES_ALFANUMERICOS = value; } }
public string TEXTO_CONTRASENHIA_CARACTERES_NUMERICOS { get { return _TEXTO_CONTRASENHIA_CARACTERES_NUMERICOS; } set { _TEXTO_CONTRASENHIA_CARACTERES_NUMERICOS = value; } }
public string TEXTO_CONTRASENHIA_DEBE_CUMPLIR { get { return _TEXTO_CONTRASENHIA_DEBE_CUMPLIR; } set { _TEXTO_CONTRASENHIA_DEBE_CUMPLIR = value; } }
public string TEXTO_CONTRASENHIA_DEBE_TENER { get { return _TEXTO_CONTRASENHIA_DEBE_TENER; } set { _TEXTO_CONTRASENHIA_DEBE_TENER = value; } }
public string TEXTO_CONTRASENHIA_ENTRE_6Y8 { get { return _TEXTO_CONTRASENHIA_ENTRE_6Y8; } set { _TEXTO_CONTRASENHIA_ENTRE_6Y8 = value; } }
public string TEXTO_CONTRASENHIA_INCLUIR_MAYUS_MINUS { get { return _TEXTO_CONTRASENHIA_INCLUIR_MAYUS_MINUS; } set { _TEXTO_CONTRASENHIA_INCLUIR_MAYUS_MINUS = value; } }
public string TEXTO_CONTRASENHIA_MAYUSCULAS { get { return _TEXTO_CONTRASENHIA_MAYUSCULAS; } set { _TEXTO_CONTRASENHIA_MAYUSCULAS = value; } }
public string TEXTO_CONTRASENHIA_MINIMO_2_CARACTERES_NUMERICOS { get { return _TEXTO_CONTRASENHIA_MINIMO_2_CARACTERES_NUMERICOS; } set { _TEXTO_CONTRASENHIA_MINIMO_2_CARACTERES_NUMERICOS = value; } }
public string TEXTO_CONTRASENHIA_MINUSCULAS { get { return _TEXTO_CONTRASENHIA_MINUSCULAS; } set { _TEXTO_CONTRASENHIA_MINUSCULAS = value; } }
public string TEXTO_CONTRASENHIA_MODIFICADA_CORRECTAMENTE { get { return _TEXTO_CONTRASENHIA_MODIFICADA_CORRECTAMENTE; } set { _TEXTO_CONTRASENHIA_MODIFICADA_CORRECTAMENTE = value; } }
public string TEXTO_CONTRASENHIA_NO_ALPHANUMERICO { get { return _TEXTO_CONTRASENHIA_NO_ALPHANUMERICO; } set { _TEXTO_CONTRASENHIA_NO_ALPHANUMERICO = value; } }
public string TEXTO_CONTRASENHIA_NO_PUEDE_ESTAR_VACIA { get { return _TEXTO_CONTRASENHIA_NO_PUEDE_ESTAR_VACIA; } set { _TEXTO_CONTRASENHIA_NO_PUEDE_ESTAR_VACIA = value; } }
public string TEXTO_CONTRASENHIA_POCO_SEGURA { get { return _TEXTO_CONTRASENHIA_POCO_SEGURA; } set { _TEXTO_CONTRASENHIA_POCO_SEGURA = value; } }
public string TEXTO_CONTRASENHIA_TIENE { get { return _TEXTO_CONTRASENHIA_TIENE; } set { _TEXTO_CONTRASENHIA_TIENE = value; } }
public string TEXTO_CONTRATO_DADO_DE_BAJA { get { return _TEXTO_CONTRATO_DADO_DE_BAJA; } set { _TEXTO_CONTRATO_DADO_DE_BAJA = value; } }
public string TEXTO_CONTRATO_MAS_DE_DOS_AVERIAS { get { return _TEXTO_CONTRATO_MAS_DE_DOS_AVERIAS; } set { _TEXTO_CONTRATO_MAS_DE_DOS_AVERIAS = value; } }
public string TEXTO_DATOS_ARGUMENTARIO { get { return _TEXTO_DATOS_ARGUMENTARIO; } set { _TEXTO_DATOS_ARGUMENTARIO = value; } }
public string TEXTO_DATOS_CALDERAS_NO_COMPLETOS { get { return _TEXTO_DATOS_CALDERAS_NO_COMPLETOS; } set { _TEXTO_DATOS_CALDERAS_NO_COMPLETOS = value; } }
public string TEXTO_DATOS_SOLICITUD { get { return _TEXTO_DATOS_SOLICITUD; } set { _TEXTO_DATOS_SOLICITUD = value; } }
public string TEXTO_DE_SEGUIR_BORRARAN_DATOS_VISITA { get { return _TEXTO_DE_SEGUIR_BORRARAN_DATOS_VISITA; } set { _TEXTO_DE_SEGUIR_BORRARAN_DATOS_VISITA = value; } }
public string TEXTO_DEBE_INIDCAR_PARAMETRO_BUSQUEDA { get { return _TEXTO_DEBE_INIDCAR_PARAMETRO_BUSQUEDA; } set { _TEXTO_DEBE_INIDCAR_PARAMETRO_BUSQUEDA = value; } }
public string TEXTO_DEBE_SELECCIONAR_CONTRATO { get { return _TEXTO_DEBE_SELECCIONAR_CONTRATO; } set { _TEXTO_DEBE_SELECCIONAR_CONTRATO = value; } }
public string TEXTO_DEBE_SELECCIONAR_ESTADO_SOLICITUD { get { return _TEXTO_DEBE_SELECCIONAR_ESTADO_SOLICITUD; } set { _TEXTO_DEBE_SELECCIONAR_ESTADO_SOLICITUD = value; } }
public string TEXTO_DEBE_SELECCIONAR_MOTIVO_CANCELACION { get { return _TEXTO_DEBE_SELECCIONAR_MOTIVO_CANCELACION; } set { _TEXTO_DEBE_SELECCIONAR_MOTIVO_CANCELACION = value; } }
public string TEXTO_DEBE_SELECCIONAR_SUBTIPO { get { return _TEXTO_DEBE_SELECCIONAR_SUBTIPO; } set { _TEXTO_DEBE_SELECCIONAR_SUBTIPO = value; } }
public string TEXTO_DEBE_SELECCIONAR_TECNICO { get { return _TEXTO_DEBE_SELECCIONAR_TECNICO; } set { _TEXTO_DEBE_SELECCIONAR_TECNICO = value; } }
public string TEXTO_DEBE_SELECCIONAR_TIPO_VISITA { get { return _TEXTO_DEBE_SELECCIONAR_TIPO_VISITA; } set { _TEXTO_DEBE_SELECCIONAR_TIPO_VISITA = value; } }
public string TEXTO_DEL_CONTRATO { get { return _TEXTO_DEL_CONTRATO; } set { _TEXTO_DEL_CONTRATO = value; } }
public string TEXTO_DEMASIADAS_COINCIDENCIAS { get { return _TEXTO_DEMASIADAS_COINCIDENCIAS; } set { _TEXTO_DEMASIADAS_COINCIDENCIAS = value; } }
public string TEXTO_DESCONECTAR { get { return _TEXTO_DESCONECTAR; } set { _TEXTO_DESCONECTAR = value; } }
public string TEXTO_DESEA_REALMENTE_DAR_BAJA { get { return _TEXTO_DESEA_REALMENTE_DAR_BAJA; } set { _TEXTO_DESEA_REALMENTE_DAR_BAJA = value; } }
public string TEXTO_ELEGIR_ACCION { get { return _TEXTO_ELEGIR_ACCION; } set { _TEXTO_ELEGIR_ACCION = value; } }
public string TEXTO_ELIMINAR_USUARIO { get { return _TEXTO_ELIMINAR_USUARIO; } set { _TEXTO_ELIMINAR_USUARIO = value; } }
public string TEXTO_EQUIPAMIENTO { get { return _TEXTO_EQUIPAMIENTO; } set { _TEXTO_EQUIPAMIENTO = value; } }
public string TEXTO_ERROR_AL_OBTENER_DATOS_SOLICITUD_ACTUAL { get { return _TEXTO_ERROR_AL_OBTENER_DATOS_SOLICITUD_ACTUAL; } set { _TEXTO_ERROR_AL_OBTENER_DATOS_SOLICITUD_ACTUAL = value; } }
public string TEXTO_ERROR_CARGA_DATOS { get { return _TEXTO_ERROR_CARGA_DATOS; } set { _TEXTO_ERROR_CARGA_DATOS = value; } }
public string TEXTO_ERROR_MOSTRAR_AVISO { get { return _TEXTO_ERROR_MOSTRAR_AVISO; } set { _TEXTO_ERROR_MOSTRAR_AVISO = value; } }
public string TEXTO_ERROR_VISITA_NO_ENCONTRADA { get { return _TEXTO_ERROR_VISITA_NO_ENCONTRADA; } set { _TEXTO_ERROR_VISITA_NO_ENCONTRADA = value; } }
public string TEXTO_ESTA_SEGURO { get { return _TEXTO_ESTA_SEGURO; } set { _TEXTO_ESTA_SEGURO = value; } }
public string TEXTO_EXCEL_DEMASIADAS_FILAS { get { return _TEXTO_EXCEL_DEMASIADAS_FILAS; } set { _TEXTO_EXCEL_DEMASIADAS_FILAS = value; } }
public string TEXTO_EXCEL_MAS_DE_10000 { get { return _TEXTO_EXCEL_MAS_DE_10000; } set { _TEXTO_EXCEL_MAS_DE_10000 = value; } }
public string TEXTO_EXPORTAR_EXCEL { get { return _TEXTO_EXPORTAR_EXCEL; } set { _TEXTO_EXPORTAR_EXCEL = value; } }
public string TEXTO_FALTA_FICHERO_OBLIGATORIO { get { return _TEXTO_FALTA_FICHERO_OBLIGATORIO; } set { _TEXTO_FALTA_FICHERO_OBLIGATORIO = value; } }
public string TEXTO_FALTAN_DATOS_OBLIGATORIOS_CALDERA { get { return _TEXTO_FALTAN_DATOS_OBLIGATORIOS_CALDERA; } set { _TEXTO_FALTAN_DATOS_OBLIGATORIOS_CALDERA = value; } }
public string TEXTO_FECHA_INTRODUCIDA_NO_PUEDE_SER_MAYOR { get { return _TEXTO_FECHA_INTRODUCIDA_NO_PUEDE_SER_MAYOR; } set { _TEXTO_FECHA_INTRODUCIDA_NO_PUEDE_SER_MAYOR = value; } }
public string TEXTO_FECHA_VISITA_NO_PUEDE_SER_INFERIOR { get { return _TEXTO_FECHA_VISITA_NO_PUEDE_SER_INFERIOR; } set { _TEXTO_FECHA_VISITA_NO_PUEDE_SER_INFERIOR = value; } }
public string TEXTO_FECHA_VISITA_NO_PUEDE_SER_MAYOR { get { return _TEXTO_FECHA_VISITA_NO_PUEDE_SER_MAYOR; } set { _TEXTO_FECHA_VISITA_NO_PUEDE_SER_MAYOR = value; } }
public string TEXTO_FECHA_VISITA_NO_PUEDE_SER_SUPERIOR { get { return _TEXTO_FECHA_VISITA_NO_PUEDE_SER_SUPERIOR; } set { _TEXTO_FECHA_VISITA_NO_PUEDE_SER_SUPERIOR = value; } }
public string TEXTO_FICHERO_EXISTENTE_BBDD { get { return _TEXTO_FICHERO_EXISTENTE_BBDD; } set { _TEXTO_FICHERO_EXISTENTE_BBDD = value; } }
public string TEXTO_FILTROS_AVANZADOS { get { return _TEXTO_FILTROS_AVANZADOS; } set { _TEXTO_FILTROS_AVANZADOS = value; } }
public string TEXTO_FILTROS_COLUMNA { get { return _TEXTO_FILTROS_COLUMNA; } set { _TEXTO_FILTROS_COLUMNA = value; } }
public string TEXTO_FORMATO_NO_AUTORIZADO { get { return _TEXTO_FORMATO_NO_AUTORIZADO; } set { _TEXTO_FORMATO_NO_AUTORIZADO = value; } }
public string TEXTO_GAS_CONFORT { get { return _TEXTO_GAS_CONFORT; } set { _TEXTO_GAS_CONFORT = value; } }
public string TEXTO_GENERADA_TRAS_LLAMADA_CORTESIA { get { return _TEXTO_GENERADA_TRAS_LLAMADA_CORTESIA; } set { _TEXTO_GENERADA_TRAS_LLAMADA_CORTESIA = value; } }
public string TEXTO_INFORMACION_POR_RECLAMACION { get { return _TEXTO_INFORMACION_POR_RECLAMACION; } set { _TEXTO_INFORMACION_POR_RECLAMACION = value; } }
public string TEXTO_LA_SOLICITUD { get { return _TEXTO_LA_SOLICITUD; } set { _TEXTO_LA_SOLICITUD = value; } }
public string TEXTO_LISTADO_BERETTA { get { return _TEXTO_LISTADO_BERETTA; } set { _TEXTO_LISTADO_BERETTA = value; } }
public string TEXTO_LISTADO_CALDERAS { get { return _TEXTO_LISTADO_CALDERAS; } set { _TEXTO_LISTADO_CALDERAS = value; } }
public string TEXTO_LISTADO_MANTENIMIENTOS { get { return _TEXTO_LISTADO_MANTENIMIENTOS; } set { _TEXTO_LISTADO_MANTENIMIENTOS = value; } }
public string TEXTO_LISTADO_SOLICITUDES { get { return _TEXTO_LISTADO_SOLICITUDES; } set { _TEXTO_LISTADO_SOLICITUDES = value; } }
public string TEXTO_MANTENIMIENTO_GAS { get { return _TEXTO_MANTENIMIENTO_GAS; } set { _TEXTO_MANTENIMIENTO_GAS = value; } }
public string TEXTO_MANTENIMIENTO_GAS_CALEFACCION { get { return _TEXTO_MANTENIMIENTO_GAS_CALEFACCION; } set { _TEXTO_MANTENIMIENTO_GAS_CALEFACCION = value; } }
public string TEXTO_MAS_DE_DOS_AVERIAS { get { return _TEXTO_MAS_DE_DOS_AVERIAS; } set { _TEXTO_MAS_DE_DOS_AVERIAS = value; } }
public string TEXTO_MOVIMIENTO_CORRECCION { get { return _TEXTO_MOVIMIENTO_CORRECCION; } set { _TEXTO_MOVIMIENTO_CORRECCION = value; } }
public string TEXTO_NINGUNO { get { return _TEXTO_NINGUNO; } set { _TEXTO_NINGUNO = value; } }
public string TEXTO_NO { get { return _TEXTO_NO; } set { _TEXTO_NO = value; } }
public string TEXTO_NO_ABRIR_AVERIAS_21_DIAS { get { return _TEXTO_NO_ABRIR_AVERIAS_21_DIAS; } set { _TEXTO_NO_ABRIR_AVERIAS_21_DIAS = value; } }
public string TEXTO_NO_ABRIR_AVERIAS_30_DIAS { get { return _TEXTO_NO_ABRIR_AVERIAS_30_DIAS; } set { _TEXTO_NO_ABRIR_AVERIAS_30_DIAS = value; } }
public string TEXTO_NO_ALTA_FALTAN_CAMPOS_OBLIGATORIOS { get { return _TEXTO_NO_ALTA_FALTAN_CAMPOS_OBLIGATORIOS; } set { _TEXTO_NO_ALTA_FALTAN_CAMPOS_OBLIGATORIOS = value; } }
public string TEXTO_NO_COINCIDEN_LOS_VALORES { get { return _TEXTO_NO_COINCIDEN_LOS_VALORES; } set { _TEXTO_NO_COINCIDEN_LOS_VALORES = value; } }
public string TEXTO_NO_DESCHEQUEAR_FACTURADO_PROVEEDOR { get { return _TEXTO_NO_DESCHEQUEAR_FACTURADO_PROVEEDOR; } set { _TEXTO_NO_DESCHEQUEAR_FACTURADO_PROVEEDOR = value; } }
public string TEXTO_NO_EXISTE_SOLICITUDES_EXPORTAR { get { return _TEXTO_NO_EXISTE_SOLICITUDES_EXPORTAR; } set { _TEXTO_NO_EXISTE_SOLICITUDES_EXPORTAR = value; } }
public string TEXTO_NO_FACTURAR_VISITA_SI_NO_CERRADA { get { return _TEXTO_NO_FACTURAR_VISITA_SI_NO_CERRADA; } set { _TEXTO_NO_FACTURAR_VISITA_SI_NO_CERRADA = value; } }
public string TEXTO_NO_HAY_CODIGO_CONTRATO { get { return _TEXTO_NO_HAY_CODIGO_CONTRATO; } set { _TEXTO_NO_HAY_CODIGO_CONTRATO = value; } }
public string TEXTO_NO_MODIFICAR_MAS_DE_21_DIAS { get { return _TEXTO_NO_MODIFICAR_MAS_DE_21_DIAS; } set { _TEXTO_NO_MODIFICAR_MAS_DE_21_DIAS = value; } }
public string TEXTO_NO_PERMITIDO_INDICAR_REPARACION { get { return _TEXTO_NO_PERMITIDO_INDICAR_REPARACION; } set { _TEXTO_NO_PERMITIDO_INDICAR_REPARACION = value; } }
public string TEXTO_NO_SE_HA_PODIDO_ALTA_SOLICITUD { get { return _TEXTO_NO_SE_HA_PODIDO_ALTA_SOLICITUD; } set { _TEXTO_NO_SE_HA_PODIDO_ALTA_SOLICITUD = value; } }
public string TEXTO_NO_SE_HA_PODIDO_MODIFICAR_SOLICITUD { get { return _TEXTO_NO_SE_HA_PODIDO_MODIFICAR_SOLICITUD; } set { _TEXTO_NO_SE_HA_PODIDO_MODIFICAR_SOLICITUD = value; } }
public string TEXTO_NO_SE_PERMITE_ENVIO_CARTA { get { return _TEXTO_NO_SE_PERMITE_ENVIO_CARTA; } set { _TEXTO_NO_SE_PERMITE_ENVIO_CARTA = value; } }
public string TEXTO_NOMBREFICHERO_INCORRECTO { get { return _TEXTO_NOMBREFICHERO_INCORRECTO; } set { _TEXTO_NOMBREFICHERO_INCORRECTO = value; } }
public string TEXTO_NUEVA_CONTRASENHIA_NP_IGUAL_ACTUAL { get { return _TEXTO_NUEVA_CONTRASENHIA_NP_IGUAL_ACTUAL; } set { _TEXTO_NUEVA_CONTRASENHIA_NP_IGUAL_ACTUAL = value; } }
public string TEXTO_NUEVO_AVISO { get { return _TEXTO_NUEVO_AVISO; } set { _TEXTO_NUEVO_AVISO = value; } }
public string TEXTO_NUEVO_AVISO_CONTRATO { get { return _TEXTO_NUEVO_AVISO_CONTRATO; } set { _TEXTO_NUEVO_AVISO_CONTRATO = value; } }
public string TEXTO_NUEVO_PAGO_ADELANTADO { get { return _TEXTO_NUEVO_PAGO_ADELANTADO; } set { _TEXTO_NUEVO_PAGO_ADELANTADO = value; } }
public string TEXTO_OCULTAR_HISTORICO { get { return _TEXTO_OCULTAR_HISTORICO; } set { _TEXTO_OCULTAR_HISTORICO = value; } }
public string TEXTO_PASSWORD_MINIMO_CARACTERES { get { return _TEXTO_PASSWORD_MINIMO_CARACTERES; } set { _TEXTO_PASSWORD_MINIMO_CARACTERES = value; } }
public string TEXTO_POR_GARANTIA_TOTAL { get { return _TEXTO_POR_GARANTIA_TOTAL; } set { _TEXTO_POR_GARANTIA_TOTAL = value; } }
public string TEXTO_REPARADA { get { return _TEXTO_REPARADA; } set { _TEXTO_REPARADA = value; } }
public string TEXTO_REPARADA_CON_DOCUMENTACION { get { return _TEXTO_REPARADA_CON_DOCUMENTACION; } set { _TEXTO_REPARADA_CON_DOCUMENTACION = value; } }
public string TEXTO_REPARADA_POR_TELEFONO { get { return _TEXTO_REPARADA_POR_TELEFONO; } set { _TEXTO_REPARADA_POR_TELEFONO = value; } }
public string TEXTO_REVISION_POR_PRECINTE { get { return _TEXTO_REVISION_POR_PRECINTE; } set { _TEXTO_REVISION_POR_PRECINTE = value; } }
public string TEXTO_SE_DEBEN_RELLENAR_CARACTERISTICAS_OBLIGATORIAS { get { return _TEXTO_SE_DEBEN_RELLENAR_CARACTERISTICAS_OBLIGATORIAS; } set { _TEXTO_SE_DEBEN_RELLENAR_CARACTERISTICAS_OBLIGATORIAS = value; } }
public string TEXTO_SEGUNDA_VEZ_AUSENTE { get { return _TEXTO_SEGUNDA_VEZ_AUSENTE; } set { _TEXTO_SEGUNDA_VEZ_AUSENTE = value; } }
public string TEXTO_SELECCIONAR_CONTRATO { get { return _TEXTO_SELECCIONAR_CONTRATO; } set { _TEXTO_SELECCIONAR_CONTRATO = value; } }
public string TEXTO_SELECCIONE_MOTIVO_CANCELACION { get { return _TEXTO_SELECCIONE_MOTIVO_CANCELACION; } set { _TEXTO_SELECCIONE_MOTIVO_CANCELACION = value; } }
public string TEXTO_SELECCIONE_TIPO_VISITA { get { return _TEXTO_SELECCIONE_TIPO_VISITA; } set { _TEXTO_SELECCIONE_TIPO_VISITA = value; } }
public string TEXTO_SERVICIO_MANTENIMIENTO_GAS { get { return _TEXTO_SERVICIO_MANTENIMIENTO_GAS; } set { _TEXTO_SERVICIO_MANTENIMIENTO_GAS = value; } }
public string TEXTO_SERVICIO_MANTENIMIENTO_GAS_CALEFACCION { get { return _TEXTO_SERVICIO_MANTENIMIENTO_GAS_CALEFACCION; } set { _TEXTO_SERVICIO_MANTENIMIENTO_GAS_CALEFACCION = value; } }
public string TEXTO_SI { get { return _TEXTO_SI; } set { _TEXTO_SI = value; } }
public string TEXTO_SOLICITUD_ABIERTA_ACTUALMENTE { get { return _TEXTO_SOLICITUD_ABIERTA_ACTUALMENTE; } set { _TEXTO_SOLICITUD_ABIERTA_ACTUALMENTE = value; } }
public string TEXTO_SOLICITUD_ALTA { get { return _TEXTO_SOLICITUD_ALTA; } set { _TEXTO_SOLICITUD_ALTA = value; } }
public string TEXTO_SOLICITUD_ALTA_CON_ENVIO_MAIL { get { return _TEXTO_SOLICITUD_ALTA_CON_ENVIO_MAIL; } set { _TEXTO_SOLICITUD_ALTA_CON_ENVIO_MAIL = value; } }
public string TEXTO_SOLICITUD_DE_VISITA { get { return _TEXTO_SOLICITUD_DE_VISITA; } set { _TEXTO_SOLICITUD_DE_VISITA = value; } }
public string TEXTO_SOLICITUD_ELIMINADA { get { return _TEXTO_SOLICITUD_ELIMINADA; } set { _TEXTO_SOLICITUD_ELIMINADA = value; } }
public string TEXTO_SOLICITUD_MODIFICADA { get { return _TEXTO_SOLICITUD_MODIFICADA; } set { _TEXTO_SOLICITUD_MODIFICADA = value; } }
public string TEXTO_SOLICITUD_MODIFICADA_CON_ENVIO_MAIL { get { return _TEXTO_SOLICITUD_MODIFICADA_CON_ENVIO_MAIL; } set { _TEXTO_SOLICITUD_MODIFICADA_CON_ENVIO_MAIL = value; } }
public string TEXTO_SOLICITUD_NO_MODIFICADA { get { return _TEXTO_SOLICITUD_NO_MODIFICADA; } set { _TEXTO_SOLICITUD_NO_MODIFICADA = value; } }
public string TEXTO_SOLICITUD_NO_RESUELTA_LLAMADA_CORTESIA { get { return _TEXTO_SOLICITUD_NO_RESUELTA_LLAMADA_CORTESIA; } set { _TEXTO_SOLICITUD_NO_RESUELTA_LLAMADA_CORTESIA = value; } }
public string TEXTO_SOLICITUD_RECLAMACION { get { return _TEXTO_SOLICITUD_RECLAMACION; } set { _TEXTO_SOLICITUD_RECLAMACION = value; } }
public string TEXTO_SOLICITUDES { get { return _TEXTO_SOLICITUDES; } set { _TEXTO_SOLICITUDES = value; } }
public string TEXTO_TAMANIO_FICHERO_INCORRECTO { get { return _TEXTO_TAMANIO_FICHERO_INCORRECTO; } set { _TEXTO_TAMANIO_FICHERO_INCORRECTO = value; } }
public string TEXTO_TECNICO_SUPERA_LIMITE_VISITAS_DIA { get { return _TEXTO_TECNICO_SUPERA_LIMITE_VISITAS_DIA; } set { _TEXTO_TECNICO_SUPERA_LIMITE_VISITAS_DIA = value; } }
public string TEXTO_TELEFONO_DEBE_COMENZAR_6789 { get { return _TEXTO_TELEFONO_DEBE_COMENZAR_6789; } set { _TEXTO_TELEFONO_DEBE_COMENZAR_6789 = value; } }
public string TEXTO_TELEFONO_DEBE_TENER_9_DIGITOS { get { return _TEXTO_TELEFONO_DEBE_TENER_9_DIGITOS; } set { _TEXTO_TELEFONO_DEBE_TENER_9_DIGITOS = value; } }
public string TEXTO_TELEFONO_OBLIGATORIO { get { return _TEXTO_TELEFONO_OBLIGATORIO; } set { _TEXTO_TELEFONO_OBLIGATORIO = value; } }
public string TEXTO_TELEFONOS_ACTUALIZADOS { get { return _TEXTO_TELEFONOS_ACTUALIZADOS; } set { _TEXTO_TELEFONOS_ACTUALIZADOS = value; } }
public string TEXTO_TODAS { get { return _TEXTO_TODAS; } set { _TEXTO_TODAS = value; } }
public string TEXTO_TODOS { get { return _TEXTO_TODOS; } set { _TEXTO_TODOS = value; } }
public string TEXTO_VALORACION_CUADRO_MANDO { get { return _TEXTO_VALORACION_CUADRO_MANDO; } set { _TEXTO_VALORACION_CUADRO_MANDO = value; } }
public string TEXTO_VER_HISTORICO { get { return _TEXTO_VER_HISTORICO; } set { _TEXTO_VER_HISTORICO = value; } }
public string TEXTO_VISITA { get { return _TEXTO_VISITA; } set { _TEXTO_VISITA = value; } }
public string TEXTO_VISITA_MODIFICAR_FACTURADA { get { return _TEXTO_VISITA_MODIFICAR_FACTURADA; } set { _TEXTO_VISITA_MODIFICAR_FACTURADA = value; } }
public string TEXTO_VISITA_REALIZADA { get { return _TEXTO_VISITA_REALIZADA; } set { _TEXTO_VISITA_REALIZADA = value; } }
public string TEXTO_VISITA_SUPERVISION { get { return _TEXTO_VISITA_SUPERVISION; } set { _TEXTO_VISITA_SUPERVISION = value; } }
public string TEXTO_VUELVA_A_SELECCIONAR_LA_SOLICITUD { get { return _TEXTO_VUELVA_A_SELECCIONAR_LA_SOLICITUD; } set { _TEXTO_VUELVA_A_SELECCIONAR_LA_SOLICITUD = value; } }
public string TEXTO_YA_LIQUIDADO_CAMBIAR_ESTADO { get { return _TEXTO_YA_LIQUIDADO_CAMBIAR_ESTADO; } set { _TEXTO_YA_LIQUIDADO_CAMBIAR_ESTADO = value; } }
public string TEXTO_YA_LIQUIDADO_ELIMINAR { get { return _TEXTO_YA_LIQUIDADO_ELIMINAR; } set { _TEXTO_YA_LIQUIDADO_ELIMINAR = value; } }
public string TEXZTO_CONTRASENHIA_CADUCADA { get { return _TEXZTO_CONTRASENHIA_CADUCADA; } set { _TEXZTO_CONTRASENHIA_CADUCADA = value; } }

public string HORARIOProveedor { get { return _HORARIOProveedor; } set { _HORARIOProveedor = value; } }


    // PORTUGUES
public string ALTA_SOLICITUD_PT { get { return _ALTA_SOLICITUD_PT; } set { _ALTA_SOLICITUD = value; } }
public string CONTRATO_NO_ENCONTRADO_PT { get { return _CONTRATO_NO_ENCONTRADO_PT; } set { _CONTRATO_NO_ENCONTRADO = value; } }
public string MODIF_SOLICITUD_PT { get { return _MODIF_SOLICITUD_PT; } set { _MODIF_SOLICITUD = value; } }
public string NUMERO_DE_INTENTOS_SUPERADOS_PT { get { return _NUMERO_DE_INTENTOS_SUPERADOS_PT; } set { _NUMERO_DE_INTENTOS_SUPERADOS = value; } }
public string SELECCIONE_SUBTIPO_SOLICITUD_PT { get { return _SELECCIONE_SUBTIPO_SOLICITUD_PT; } set { _SELECCIONE_SUBTIPO_SOLICITUD = value; } }
public string SELECCIONE_TIPO_AVERIA_PT { get { return _SELECCIONE_TIPO_AVERIA_PT; } set { _SELECCIONE_TIPO_AVERIA = value; } }
public string SERVICIO_DADO_DE_BAJA_PT { get { return _SERVICIO_DADO_DE_BAJA_PT; } set { _SERVICIO_DADO_DE_BAJA = value; } }
public string TEXTO_ACEPTACION_DE_PRESUPUESTO_PT { get { return _TEXTO_ACEPTACION_DE_PRESUPUESTO_PT; } set { _TEXTO_ACEPTACION_DE_PRESUPUESTO = value; } }
public string TEXTO_ADMINISTRACION_PT { get { return _TEXTO_ADMINISTRACION_PT; } set { _TEXTO_ADMINISTRACION = value; } }
public string TEXTO_ALERTA_PT { get { return _TEXTO_ALERTA_PT; } set { _TEXTO_ALERTA = value; } }
public string TEXTO_ALTA_AVERIA_GAS_CONFORT_PT { get { return _TEXTO_ALTA_AVERIA_GAS_CONFORT_PT; } set { _TEXTO_ALTA_AVERIA_GAS_CONFORT = value; } }
public string TEXTO_ALTA_AVERIA_GAS_CONFORT_TITULO_PT { get { return _TEXTO_ALTA_AVERIA_GAS_CONFORT_TITULO_PT; } set { _TEXTO_ALTA_AVERIA_GAS_CONFORT_TITULO = value; } }
public string TEXTO_ALTA_GAS_CONFORT_PT { get { return _TEXTO_ALTA_GAS_CONFORT_PT; } set { _TEXTO_ALTA_GAS_CONFORT = value; } }
public string TEXTO_ATENCION_AVERIA_ABIERTA_PT { get { return _TEXTO_ATENCION_AVERIA_ABIERTA_PT; } set { _TEXTO_ATENCION_AVERIA_ABIERTA = value; } }
public string TEXTO_ATENCION_CONTRATO_BAJA_PT { get { return _TEXTO_ATENCION_CONTRATO_BAJA_PT; } set { _TEXTO_ATENCION_CONTRATO_BAJA = value; } }
public string TEXTO_ATENCION_CONTRATO_BAJA_POR_RECLAMACION_PT { get { return _TEXTO_ATENCION_CONTRATO_BAJA_POR_RECLAMACION_PT; } set { _TEXTO_ATENCION_CONTRATO_BAJA_POR_RECLAMACION = value; } }
public string TEXTO_ATENCION_SOLICITUD_NO_PUEDE_DERIVARSE_PT { get { return _TEXTO_ATENCION_SOLICITUD_NO_PUEDE_DERIVARSE_PT; } set { _TEXTO_ATENCION_SOLICITUD_NO_PUEDE_DERIVARSE = value; } }
public string TEXTO_AVERIA_PT { get { return _TEXTO_AVERIA_PT; } set { _TEXTO_AVERIA = value; } }
public string TEXTO_AVERIA_GAS_CONFORT_PT { get { return _TEXTO_AVERIA_GAS_CONFORT_PT; } set { _TEXTO_AVERIA_GAS_CONFORT = value; } }
public string TEXTO_AVERIA_INCORRECTA_PT { get { return _TEXTO_AVERIA_INCORRECTA_PT; } set { _TEXTO_AVERIA_INCORRECTA = value; } }
public string TEXTO_AVERIA_INCORRECTA_GAS_CONFORT_PT { get { return _TEXTO_AVERIA_INCORRECTA_GAS_CONFORT_PT; } set { _TEXTO_AVERIA_INCORRECTA_GAS_CONFORT = value; } }
public string TEXTO_AVERIA_MANTENIMIENTO_PT { get { return _TEXTO_AVERIA_MANTENIMIENTO_PT; } set { _TEXTO_AVERIA_MANTENIMIENTO = value; } }
public string TEXTO_AVISO_PT { get { return _TEXTO_AVISO_PT; } set { _TEXTO_AVISO = value; } }
public string TEXTO_BAJA_SERVICIO_PT { get { return _TEXTO_BAJA_SERVICIO_PT; } set { _TEXTO_BAJA_SERVICIO = value; } }
public string TEXTO_BUSCAR_USUARIO_PT { get { return _TEXTO_BUSCAR_USUARIO_PT; } set { _TEXTO_BUSCAR_USUARIO = value; } }
public string TEXTO_CALDERAS_PT { get { return _TEXTO_CALDERAS_PT; } set { _TEXTO_CALDERAS = value; } }
public string TEXTO_CANCELADA_PT { get { return _TEXTO_CANCELADA_PT; } set { _TEXTO_CANCELADA = value; } }
public string TEXTO_CANCELADA_POR_REASIGNACION_PT { get { return _TEXTO_CANCELADA_POR_REASIGNACION_PT; } set { _TEXTO_CANCELADA_POR_REASIGNACION = value; } }
public string TEXTO_CANCELADA_POR_SISTEMA_PT { get { return _TEXTO_CANCELADA_POR_SISTEMA_PT; } set { _TEXTO_CANCELADA_POR_SISTEMA = value; } }
public string TEXTO_CANCELADO_TRANSFERIDO_A_SAT_PT { get { return _TEXTO_CANCELADO_TRANSFERIDO_A_SAT_PT; } set { _TEXTO_CANCELADO_TRANSFERIDO_A_SAT = value; } }
public string TEXTO_CLIENTE_PREFERENTE_FACEBOOK_PT { get { return _TEXTO_CLIENTE_PREFERENTE_FACEBOOK_PT; } set { _TEXTO_CLIENTE_PREFERENTE_FACEBOOK = value; } }
public string TEXTO_CLIENTE_PREFERENTE_TWITTER_PT { get { return _TEXTO_CLIENTE_PREFERENTE_TWITTER_PT; } set { _TEXTO_CLIENTE_PREFERENTE_TWITTER = value; } }
public string TEXTO_COBERTURA_SERVICIO_PT { get { return _TEXTO_COBERTURA_SERVICIO_PT; } set { _TEXTO_COBERTURA_SERVICIO = value; } }
public string TEXTO_CODIFICACION_AVERIAS_PT { get { return _TEXTO_CODIFICACION_AVERIAS_PT; } set { _TEXTO_CODIFICACION_AVERIAS = value; } }
public string TEXTO_CODIGO_AVERIA_OBLIGATORIO_PT { get { return _TEXTO_CODIGO_AVERIA_OBLIGATORIO_PT; } set { _TEXTO_CODIGO_AVERIA_OBLIGATORIO = value; } }
public string TEXTO_CODIGO_SOLICITUD_PT { get { return _TEXTO_CODIGO_SOLICITUD_PT; } set { _TEXTO_CODIGO_SOLICITUD = value; } }
public string TEXTO_CODIGO_VISITA_OBLIGATORIO_PT { get { return _TEXTO_CODIGO_VISITA_OBLIGATORIO_PT; } set { _TEXTO_CODIGO_VISITA_OBLIGATORIO = value; } }
public string TEXTO_COMPRUEBE_DATOS_BANCARIOS_PT { get { return _TEXTO_COMPRUEBE_DATOS_BANCARIOS_PT; } set { _TEXTO_COMPRUEBE_DATOS_BANCARIOS = value; } }
public string TEXTO_COMPRUEBE_DATOS_OBLIGATORIOS_PT { get { return _TEXTO_COMPRUEBE_DATOS_OBLIGATORIOS_PT; } set { _TEXTO_COMPRUEBE_DATOS_OBLIGATORIOS = value; } }
public string TEXTO_COMPRUEBE_FECHA_INTRODUCIDA_PT { get { return _TEXTO_COMPRUEBE_FECHA_INTRODUCIDA_PT; } set { _TEXTO_COMPRUEBE_FECHA_INTRODUCIDA = value; } }
public string TEXTO_COMPRUEBE_IMPORTE_INTRODUCIDO_PT { get { return _TEXTO_COMPRUEBE_IMPORTE_INTRODUCIDO_PT; } set { _TEXTO_COMPRUEBE_IMPORTE_INTRODUCIDO = value; } }
public string TEXTO_COMPRUEBE_NUMERO_SERIE_TERMOSTATO_PT { get { return _TEXTO_COMPRUEBE_NUMERO_SERIE_TERMOSTATO_PT; } set { _TEXTO_COMPRUEBE_NUMERO_SERIE_TERMOSTATO = value; } }
public string TEXTO_CON_CUOTA_PT { get { return _TEXTO_CON_CUOTA_PT; } set { _TEXTO_CON_CUOTA = value; } }
public string TEXTO_CON_PAGO_FRACCIONADO_PT { get { return _TEXTO_CON_PAGO_FRACCIONADO_PT; } set { _TEXTO_CON_PAGO_FRACCIONADO = value; } }
public string TEXTO_CONFIRMACION_PASSWORD_NO_VACIA_PT { get { return _TEXTO_CONFIRMACION_PASSWORD_NO_VACIA_PT; } set { _TEXTO_CONFIRMACION_PASSWORD_NO_VACIA = value; } }
public string TEXTO_CONTRASENHIA_CARACTERES_ALFANUMERICOS_PT { get { return _TEXTO_CONTRASENHIA_CARACTERES_ALFANUMERICOS_PT; } set { _TEXTO_CONTRASENHIA_CARACTERES_ALFANUMERICOS = value; } }
public string TEXTO_CONTRASENHIA_CARACTERES_NUMERICOS_PT { get { return _TEXTO_CONTRASENHIA_CARACTERES_NUMERICOS_PT; } set { _TEXTO_CONTRASENHIA_CARACTERES_NUMERICOS = value; } }
public string TEXTO_CONTRASENHIA_DEBE_CUMPLIR_PT { get { return _TEXTO_CONTRASENHIA_DEBE_CUMPLIR_PT; } set { _TEXTO_CONTRASENHIA_DEBE_CUMPLIR = value; } }
public string TEXTO_CONTRASENHIA_DEBE_TENER_PT { get { return _TEXTO_CONTRASENHIA_DEBE_TENER_PT; } set { _TEXTO_CONTRASENHIA_DEBE_TENER = value; } }
public string TEXTO_CONTRASENHIA_ENTRE_6Y8_PT { get { return _TEXTO_CONTRASENHIA_ENTRE_6Y8_PT; } set { _TEXTO_CONTRASENHIA_ENTRE_6Y8 = value; } }
public string TEXTO_CONTRASENHIA_INCLUIR_MAYUS_MINUS_PT { get { return _TEXTO_CONTRASENHIA_INCLUIR_MAYUS_MINUS_PT; } set { _TEXTO_CONTRASENHIA_INCLUIR_MAYUS_MINUS = value; } }
public string TEXTO_CONTRASENHIA_MAYUSCULAS_PT { get { return _TEXTO_CONTRASENHIA_MAYUSCULAS_PT; } set { _TEXTO_CONTRASENHIA_MAYUSCULAS = value; } }
public string TEXTO_CONTRASENHIA_MINIMO_2_CARACTERES_NUMERICOS_PT { get { return _TEXTO_CONTRASENHIA_MINIMO_2_CARACTERES_NUMERICOS_PT; } set { _TEXTO_CONTRASENHIA_MINIMO_2_CARACTERES_NUMERICOS = value; } }
public string TEXTO_CONTRASENHIA_MINUSCULAS_PT { get { return _TEXTO_CONTRASENHIA_MINUSCULAS_PT; } set { _TEXTO_CONTRASENHIA_MINUSCULAS = value; } }
public string TEXTO_CONTRASENHIA_MODIFICADA_CORRECTAMENTE_PT { get { return _TEXTO_CONTRASENHIA_MODIFICADA_CORRECTAMENTE_PT; } set { _TEXTO_CONTRASENHIA_MODIFICADA_CORRECTAMENTE = value; } }
public string TEXTO_CONTRASENHIA_NO_ALPHANUMERICO_PT { get { return _TEXTO_CONTRASENHIA_NO_ALPHANUMERICO_PT; } set { _TEXTO_CONTRASENHIA_NO_ALPHANUMERICO = value; } }
public string TEXTO_CONTRASENHIA_NO_PUEDE_ESTAR_VACIA_PT { get { return _TEXTO_CONTRASENHIA_NO_PUEDE_ESTAR_VACIA_PT; } set { _TEXTO_CONTRASENHIA_NO_PUEDE_ESTAR_VACIA = value; } }
public string TEXTO_CONTRASENHIA_POCO_SEGURA_PT { get { return _TEXTO_CONTRASENHIA_POCO_SEGURA_PT; } set { _TEXTO_CONTRASENHIA_POCO_SEGURA = value; } }
public string TEXTO_CONTRASENHIA_TIENE_PT { get { return _TEXTO_CONTRASENHIA_TIENE_PT; } set { _TEXTO_CONTRASENHIA_TIENE = value; } }
public string TEXTO_CONTRATO_DADO_DE_BAJA_PT { get { return _TEXTO_CONTRATO_DADO_DE_BAJA_PT; } set { _TEXTO_CONTRATO_DADO_DE_BAJA = value; } }
public string TEXTO_CONTRATO_MAS_DE_DOS_AVERIAS_PT { get { return _TEXTO_CONTRATO_MAS_DE_DOS_AVERIAS_PT; } set { _TEXTO_CONTRATO_MAS_DE_DOS_AVERIAS = value; } }
public string TEXTO_DATOS_ARGUMENTARIO_PT { get { return _TEXTO_DATOS_ARGUMENTARIO_PT; } set { _TEXTO_DATOS_ARGUMENTARIO = value; } }
public string TEXTO_DATOS_CALDERAS_NO_COMPLETOS_PT { get { return _TEXTO_DATOS_CALDERAS_NO_COMPLETOS_PT; } set { _TEXTO_DATOS_CALDERAS_NO_COMPLETOS = value; } }
public string TEXTO_DATOS_SOLICITUD_PT { get { return _TEXTO_DATOS_SOLICITUD_PT; } set { _TEXTO_DATOS_SOLICITUD = value; } }
public string TEXTO_DE_SEGUIR_BORRARAN_DATOS_VISITA_PT { get { return _TEXTO_DE_SEGUIR_BORRARAN_DATOS_VISITA_PT; } set { _TEXTO_DE_SEGUIR_BORRARAN_DATOS_VISITA = value; } }
public string TEXTO_DEBE_INIDCAR_PARAMETRO_BUSQUEDA_PT { get { return _TEXTO_DEBE_INIDCAR_PARAMETRO_BUSQUEDA_PT; } set { _TEXTO_DEBE_INIDCAR_PARAMETRO_BUSQUEDA = value; } }
public string TEXTO_DEBE_SELECCIONAR_CONTRATO_PT { get { return _TEXTO_DEBE_SELECCIONAR_CONTRATO_PT; } set { _TEXTO_DEBE_SELECCIONAR_CONTRATO = value; } }
public string TEXTO_DEBE_SELECCIONAR_ESTADO_SOLICITUD_PT { get { return _TEXTO_DEBE_SELECCIONAR_ESTADO_SOLICITUD_PT; } set { _TEXTO_DEBE_SELECCIONAR_ESTADO_SOLICITUD = value; } }
public string TEXTO_DEBE_SELECCIONAR_MOTIVO_CANCELACION_PT { get { return _TEXTO_DEBE_SELECCIONAR_MOTIVO_CANCELACION_PT; } set { _TEXTO_DEBE_SELECCIONAR_MOTIVO_CANCELACION = value; } }
public string TEXTO_DEBE_SELECCIONAR_SUBTIPO_PT { get { return _TEXTO_DEBE_SELECCIONAR_SUBTIPO_PT; } set { _TEXTO_DEBE_SELECCIONAR_SUBTIPO = value; } }
public string TEXTO_DEBE_SELECCIONAR_TECNICO_PT { get { return _TEXTO_DEBE_SELECCIONAR_TECNICO_PT; } set { _TEXTO_DEBE_SELECCIONAR_TECNICO = value; } }
public string TEXTO_DEBE_SELECCIONAR_TIPO_VISITA_PT { get { return _TEXTO_DEBE_SELECCIONAR_TIPO_VISITA_PT; } set { _TEXTO_DEBE_SELECCIONAR_TIPO_VISITA = value; } }
public string TEXTO_DEL_CONTRATO_PT { get { return _TEXTO_DEL_CONTRATO_PT; } set { _TEXTO_DEL_CONTRATO = value; } }
public string TEXTO_DEMASIADAS_COINCIDENCIAS_PT { get { return _TEXTO_DEMASIADAS_COINCIDENCIAS_PT; } set { _TEXTO_DEMASIADAS_COINCIDENCIAS = value; } }
public string TEXTO_DESCONECTAR_PT { get { return _TEXTO_DESCONECTAR_PT; } set { _TEXTO_DESCONECTAR = value; } }
public string TEXTO_DESEA_REALMENTE_DAR_BAJA_PT { get { return _TEXTO_DESEA_REALMENTE_DAR_BAJA_PT; } set { _TEXTO_DESEA_REALMENTE_DAR_BAJA = value; } }
public string TEXTO_ELEGIR_ACCION_PT { get { return _TEXTO_ELEGIR_ACCION_PT; } set { _TEXTO_ELEGIR_ACCION = value; } }
public string TEXTO_ELIMINAR_USUARIO_PT { get { return _TEXTO_ELIMINAR_USUARIO_PT; } set { _TEXTO_ELIMINAR_USUARIO = value; } }
public string TEXTO_EQUIPAMIENTO_PT { get { return _TEXTO_EQUIPAMIENTO_PT; } set { _TEXTO_EQUIPAMIENTO = value; } }
public string TEXTO_ERROR_AL_OBTENER_DATOS_SOLICITUD_ACTUAL_PT { get { return _TEXTO_ERROR_AL_OBTENER_DATOS_SOLICITUD_ACTUAL_PT; } set { _TEXTO_ERROR_AL_OBTENER_DATOS_SOLICITUD_ACTUAL = value; } }
public string TEXTO_ERROR_CARGA_DATOS_PT { get { return _TEXTO_ERROR_CARGA_DATOS_PT; } set { _TEXTO_ERROR_CARGA_DATOS = value; } }
public string TEXTO_ERROR_MOSTRAR_AVISO_PT { get { return _TEXTO_ERROR_MOSTRAR_AVISO_PT; } set { _TEXTO_ERROR_MOSTRAR_AVISO = value; } }
public string TEXTO_ERROR_VISITA_NO_ENCONTRADA_PT { get { return _TEXTO_ERROR_VISITA_NO_ENCONTRADA_PT; } set { _TEXTO_ERROR_VISITA_NO_ENCONTRADA = value; } }
public string TEXTO_ESTA_SEGURO_PT { get { return _TEXTO_ESTA_SEGURO_PT; } set { _TEXTO_ESTA_SEGURO = value; } }
public string TEXTO_EXCEL_DEMASIADAS_FILAS_PT { get { return _TEXTO_EXCEL_DEMASIADAS_FILAS_PT; } set { _TEXTO_EXCEL_DEMASIADAS_FILAS = value; } }
public string TEXTO_EXCEL_MAS_DE_10000_PT { get { return _TEXTO_EXCEL_MAS_DE_10000_PT; } set { _TEXTO_EXCEL_MAS_DE_10000 = value; } }
public string TEXTO_EXPORTAR_EXCEL_PT { get { return _TEXTO_EXPORTAR_EXCEL_PT; } set { _TEXTO_EXPORTAR_EXCEL = value; } }
public string TEXTO_FALTA_FICHERO_OBLIGATORIO_PT { get { return _TEXTO_FALTA_FICHERO_OBLIGATORIO_PT; } set { _TEXTO_FALTA_FICHERO_OBLIGATORIO = value; } }
public string TEXTO_FALTAN_DATOS_OBLIGATORIOS_CALDERA_PT { get { return _TEXTO_FALTAN_DATOS_OBLIGATORIOS_CALDERA_PT; } set { _TEXTO_FALTAN_DATOS_OBLIGATORIOS_CALDERA = value; } }
public string TEXTO_FECHA_INTRODUCIDA_NO_PUEDE_SER_MAYOR_PT { get { return _TEXTO_FECHA_INTRODUCIDA_NO_PUEDE_SER_MAYOR_PT; } set { _TEXTO_FECHA_INTRODUCIDA_NO_PUEDE_SER_MAYOR = value; } }
public string TEXTO_FECHA_VISITA_NO_PUEDE_SER_INFERIOR_PT { get { return _TEXTO_FECHA_VISITA_NO_PUEDE_SER_INFERIOR_PT; } set { _TEXTO_FECHA_VISITA_NO_PUEDE_SER_INFERIOR = value; } }
public string TEXTO_FECHA_VISITA_NO_PUEDE_SER_MAYOR_PT { get { return _TEXTO_FECHA_VISITA_NO_PUEDE_SER_MAYOR_PT; } set { _TEXTO_FECHA_VISITA_NO_PUEDE_SER_MAYOR = value; } }
public string TEXTO_FECHA_VISITA_NO_PUEDE_SER_SUPERIOR_PT { get { return _TEXTO_FECHA_VISITA_NO_PUEDE_SER_SUPERIOR_PT; } set { _TEXTO_FECHA_VISITA_NO_PUEDE_SER_SUPERIOR = value; } }
public string TEXTO_FICHERO_EXISTENTE_BBDD_PT { get { return _TEXTO_FICHERO_EXISTENTE_BBDD_PT; } set { _TEXTO_FICHERO_EXISTENTE_BBDD = value; } }
public string TEXTO_FILTROS_AVANZADOS_PT { get { return _TEXTO_FILTROS_AVANZADOS_PT; } set { _TEXTO_FILTROS_AVANZADOS = value; } }
public string TEXTO_FILTROS_COLUMNA_PT { get { return _TEXTO_FILTROS_COLUMNA_PT; } set { _TEXTO_FILTROS_COLUMNA = value; } }
public string TEXTO_FORMATO_NO_AUTORIZADO_PT { get { return _TEXTO_FORMATO_NO_AUTORIZADO_PT; } set { _TEXTO_FORMATO_NO_AUTORIZADO = value; } }
public string TEXTO_GAS_CONFORT_PT { get { return _TEXTO_GAS_CONFORT_PT; } set { _TEXTO_GAS_CONFORT = value; } }
public string TEXTO_GENERADA_TRAS_LLAMADA_CORTESIA_PT { get { return _TEXTO_GENERADA_TRAS_LLAMADA_CORTESIA_PT; } set { _TEXTO_GENERADA_TRAS_LLAMADA_CORTESIA = value; } }
public string TEXTO_INFORMACION_POR_RECLAMACION_PT { get { return _TEXTO_INFORMACION_POR_RECLAMACION_PT; } set { _TEXTO_INFORMACION_POR_RECLAMACION = value; } }
public string TEXTO_LA_SOLICITUD_PT { get { return _TEXTO_LA_SOLICITUD_PT; } set { _TEXTO_LA_SOLICITUD = value; } }
public string TEXTO_LISTADO_BERETTA_PT { get { return _TEXTO_LISTADO_BERETTA_PT; } set { _TEXTO_LISTADO_BERETTA = value; } }
public string TEXTO_LISTADO_CALDERAS_PT { get { return _TEXTO_LISTADO_CALDERAS_PT; } set { _TEXTO_LISTADO_CALDERAS = value; } }
public string TEXTO_LISTADO_MANTENIMIENTOS_PT { get { return _TEXTO_LISTADO_MANTENIMIENTOS_PT; } set { _TEXTO_LISTADO_MANTENIMIENTOS = value; } }
public string TEXTO_LISTADO_SOLICITUDES_PT { get { return _TEXTO_LISTADO_SOLICITUDES_PT; } set { _TEXTO_LISTADO_SOLICITUDES = value; } }
public string TEXTO_MANTENIMIENTO_GAS_PT { get { return _TEXTO_MANTENIMIENTO_GAS_PT; } set { _TEXTO_MANTENIMIENTO_GAS = value; } }
public string TEXTO_MANTENIMIENTO_GAS_CALEFACCION_PT { get { return _TEXTO_MANTENIMIENTO_GAS_CALEFACCION_PT; } set { _TEXTO_MANTENIMIENTO_GAS_CALEFACCION = value; } }
public string TEXTO_MAS_DE_DOS_AVERIAS_PT { get { return _TEXTO_MAS_DE_DOS_AVERIAS_PT; } set { _TEXTO_MAS_DE_DOS_AVERIAS = value; } }
public string TEXTO_MOVIMIENTO_CORRECCION_PT { get { return _TEXTO_MOVIMIENTO_CORRECCION_PT; } set { _TEXTO_MOVIMIENTO_CORRECCION = value; } }
public string TEXTO_NINGUNO_PT { get { return _TEXTO_NINGUNO_PT; } set { _TEXTO_NINGUNO = value; } }
public string TEXTO_NO_PT { get { return _TEXTO_NO_PT; } set { _TEXTO_NO = value; } }
public string TEXTO_NO_ABRIR_AVERIAS_21_DIAS_PT { get { return _TEXTO_NO_ABRIR_AVERIAS_21_DIAS_PT; } set { _TEXTO_NO_ABRIR_AVERIAS_21_DIAS = value; } }
public string TEXTO_NO_ABRIR_AVERIAS_30_DIAS_PT { get { return _TEXTO_NO_ABRIR_AVERIAS_30_DIAS_PT; } set { _TEXTO_NO_ABRIR_AVERIAS_30_DIAS = value; } }
public string TEXTO_NO_ALTA_FALTAN_CAMPOS_OBLIGATORIOS_PT { get { return _TEXTO_NO_ALTA_FALTAN_CAMPOS_OBLIGATORIOS_PT; } set { _TEXTO_NO_ALTA_FALTAN_CAMPOS_OBLIGATORIOS = value; } }
public string TEXTO_NO_COINCIDEN_LOS_VALORES_PT { get { return _TEXTO_NO_COINCIDEN_LOS_VALORES_PT; } set { _TEXTO_NO_COINCIDEN_LOS_VALORES = value; } }
public string TEXTO_NO_DESCHEQUEAR_FACTURADO_PROVEEDOR_PT { get { return _TEXTO_NO_DESCHEQUEAR_FACTURADO_PROVEEDOR_PT; } set { _TEXTO_NO_DESCHEQUEAR_FACTURADO_PROVEEDOR = value; } }
public string TEXTO_NO_EXISTE_SOLICITUDES_EXPORTAR_PT { get { return _TEXTO_NO_EXISTE_SOLICITUDES_EXPORTAR_PT; } set { _TEXTO_NO_EXISTE_SOLICITUDES_EXPORTAR = value; } }
public string TEXTO_NO_FACTURAR_VISITA_SI_NO_CERRADA_PT { get { return _TEXTO_NO_FACTURAR_VISITA_SI_NO_CERRADA_PT; } set { _TEXTO_NO_FACTURAR_VISITA_SI_NO_CERRADA = value; } }
public string TEXTO_NO_HAY_CODIGO_CONTRATO_PT { get { return _TEXTO_NO_HAY_CODIGO_CONTRATO_PT; } set { _TEXTO_NO_HAY_CODIGO_CONTRATO = value; } }
public string TEXTO_NO_MODIFICAR_MAS_DE_21_DIAS_PT { get { return _TEXTO_NO_MODIFICAR_MAS_DE_21_DIAS_PT; } set { _TEXTO_NO_MODIFICAR_MAS_DE_21_DIAS = value; } }
public string TEXTO_NO_PERMITIDO_INDICAR_REPARACION_PT { get { return _TEXTO_NO_PERMITIDO_INDICAR_REPARACION_PT; } set { _TEXTO_NO_PERMITIDO_INDICAR_REPARACION = value; } }
public string TEXTO_NO_SE_HA_PODIDO_ALTA_SOLICITUD_PT { get { return _TEXTO_NO_SE_HA_PODIDO_ALTA_SOLICITUD_PT; } set { _TEXTO_NO_SE_HA_PODIDO_ALTA_SOLICITUD = value; } }
public string TEXTO_NO_SE_HA_PODIDO_MODIFICAR_SOLICITUD_PT { get { return _TEXTO_NO_SE_HA_PODIDO_MODIFICAR_SOLICITUD_PT; } set { _TEXTO_NO_SE_HA_PODIDO_MODIFICAR_SOLICITUD = value; } }
public string TEXTO_NO_SE_PERMITE_ENVIO_CARTA_PT { get { return _TEXTO_NO_SE_PERMITE_ENVIO_CARTA_PT; } set { _TEXTO_NO_SE_PERMITE_ENVIO_CARTA = value; } }
public string TEXTO_NOMBREFICHERO_INCORRECTO_PT { get { return _TEXTO_NOMBREFICHERO_INCORRECTO_PT; } set { _TEXTO_NOMBREFICHERO_INCORRECTO = value; } }
public string TEXTO_NUEVA_CONTRASENHIA_NP_IGUAL_ACTUAL_PT { get { return _TEXTO_NUEVA_CONTRASENHIA_NP_IGUAL_ACTUAL_PT; } set { _TEXTO_NUEVA_CONTRASENHIA_NP_IGUAL_ACTUAL = value; } }
public string TEXTO_NUEVO_AVISO_PT { get { return _TEXTO_NUEVO_AVISO_PT; } set { _TEXTO_NUEVO_AVISO = value; } }
public string TEXTO_NUEVO_AVISO_CONTRATO_PT { get { return _TEXTO_NUEVO_AVISO_CONTRATO_PT; } set { _TEXTO_NUEVO_AVISO_CONTRATO = value; } }
public string TEXTO_NUEVO_PAGO_ADELANTADO_PT { get { return _TEXTO_NUEVO_PAGO_ADELANTADO_PT; } set { _TEXTO_NUEVO_PAGO_ADELANTADO = value; } }
public string TEXTO_OCULTAR_HISTORICO_PT { get { return _TEXTO_OCULTAR_HISTORICO_PT; } set { _TEXTO_OCULTAR_HISTORICO = value; } }
public string TEXTO_PASSWORD_MINIMO_CARACTERES_PT { get { return _TEXTO_PASSWORD_MINIMO_CARACTERES_PT; } set { _TEXTO_PASSWORD_MINIMO_CARACTERES = value; } }
public string TEXTO_POR_GARANTIA_TOTAL_PT { get { return _TEXTO_POR_GARANTIA_TOTAL_PT; } set { _TEXTO_POR_GARANTIA_TOTAL = value; } }
public string TEXTO_REPARADA_PT { get { return _TEXTO_REPARADA_PT; } set { _TEXTO_REPARADA = value; } }
public string TEXTO_REPARADA_CON_DOCUMENTACION_PT { get { return _TEXTO_REPARADA_CON_DOCUMENTACION_PT; } set { _TEXTO_REPARADA_CON_DOCUMENTACION = value; } }
public string TEXTO_REPARADA_POR_TELEFONO_PT { get { return _TEXTO_REPARADA_POR_TELEFONO_PT; } set { _TEXTO_REPARADA_POR_TELEFONO = value; } }
public string TEXTO_REVISION_POR_PRECINTE_PT { get { return _TEXTO_REVISION_POR_PRECINTE_PT; } set { _TEXTO_REVISION_POR_PRECINTE = value; } }
public string TEXTO_SE_DEBEN_RELLENAR_CARACTERISTICAS_OBLIGATORIAS_PT { get { return _TEXTO_SE_DEBEN_RELLENAR_CARACTERISTICAS_OBLIGATORIAS_PT; } set { _TEXTO_SE_DEBEN_RELLENAR_CARACTERISTICAS_OBLIGATORIAS = value; } }
public string TEXTO_SEGUNDA_VEZ_AUSENTE_PT { get { return _TEXTO_SEGUNDA_VEZ_AUSENTE_PT; } set { _TEXTO_SEGUNDA_VEZ_AUSENTE = value; } }
public string TEXTO_SELECCIONAR_CONTRATO_PT { get { return _TEXTO_SELECCIONAR_CONTRATO_PT; } set { _TEXTO_SELECCIONAR_CONTRATO = value; } }
public string TEXTO_SELECCIONE_MOTIVO_CANCELACION_PT { get { return _TEXTO_SELECCIONE_MOTIVO_CANCELACION_PT; } set { _TEXTO_SELECCIONE_MOTIVO_CANCELACION = value; } }
public string TEXTO_SELECCIONE_TIPO_VISITA_PT { get { return _TEXTO_SELECCIONE_TIPO_VISITA_PT; } set { _TEXTO_SELECCIONE_TIPO_VISITA = value; } }
public string TEXTO_SERVICIO_MANTENIMIENTO_GAS_PT { get { return _TEXTO_SERVICIO_MANTENIMIENTO_GAS_PT; } set { _TEXTO_SERVICIO_MANTENIMIENTO_GAS = value; } }
public string TEXTO_SERVICIO_MANTENIMIENTO_GAS_CALEFACCION_PT { get { return _TEXTO_SERVICIO_MANTENIMIENTO_GAS_CALEFACCION_PT; } set { _TEXTO_SERVICIO_MANTENIMIENTO_GAS_CALEFACCION = value; } }
public string TEXTO_SI_PT { get { return _TEXTO_SI_PT; } set { _TEXTO_SI = value; } }
public string TEXTO_SOLICITUD_ABIERTA_ACTUALMENTE_PT { get { return _TEXTO_SOLICITUD_ABIERTA_ACTUALMENTE_PT; } set { _TEXTO_SOLICITUD_ABIERTA_ACTUALMENTE = value; } }
public string TEXTO_SOLICITUD_ALTA_PT { get { return _TEXTO_SOLICITUD_ALTA_PT; } set { _TEXTO_SOLICITUD_ALTA = value; } }
public string TEXTO_SOLICITUD_ALTA_CON_ENVIO_MAIL_PT { get { return _TEXTO_SOLICITUD_ALTA_CON_ENVIO_MAIL_PT; } set { _TEXTO_SOLICITUD_ALTA_CON_ENVIO_MAIL = value; } }
public string TEXTO_SOLICITUD_DE_VISITA_PT { get { return _TEXTO_SOLICITUD_DE_VISITA_PT; } set { _TEXTO_SOLICITUD_DE_VISITA = value; } }
public string TEXTO_SOLICITUD_ELIMINADA_PT { get { return _TEXTO_SOLICITUD_ELIMINADA_PT; } set { _TEXTO_SOLICITUD_ELIMINADA = value; } }
public string TEXTO_SOLICITUD_MODIFICADA_PT { get { return _TEXTO_SOLICITUD_MODIFICADA_PT; } set { _TEXTO_SOLICITUD_MODIFICADA = value; } }
public string TEXTO_SOLICITUD_MODIFICADA_CON_ENVIO_MAIL_PT { get { return _TEXTO_SOLICITUD_MODIFICADA_CON_ENVIO_MAIL_PT; } set { _TEXTO_SOLICITUD_MODIFICADA_CON_ENVIO_MAIL = value; } }
public string TEXTO_SOLICITUD_NO_MODIFICADA_PT { get { return _TEXTO_SOLICITUD_NO_MODIFICADA_PT; } set { _TEXTO_SOLICITUD_NO_MODIFICADA = value; } }
public string TEXTO_SOLICITUD_NO_RESUELTA_LLAMADA_CORTESIA_PT { get { return _TEXTO_SOLICITUD_NO_RESUELTA_LLAMADA_CORTESIA_PT; } set { _TEXTO_SOLICITUD_NO_RESUELTA_LLAMADA_CORTESIA = value; } }
public string TEXTO_SOLICITUD_RECLAMACION_PT { get { return _TEXTO_SOLICITUD_RECLAMACION_PT; } set { _TEXTO_SOLICITUD_RECLAMACION = value; } }
public string TEXTO_SOLICITUDES_PT { get { return _TEXTO_SOLICITUDES_PT; } set { _TEXTO_SOLICITUDES = value; } }
public string TEXTO_TAMANIO_FICHERO_INCORRECTO_PT { get { return _TEXTO_TAMANIO_FICHERO_INCORRECTO_PT; } set { _TEXTO_TAMANIO_FICHERO_INCORRECTO = value; } }
public string TEXTO_TECNICO_SUPERA_LIMITE_VISITAS_DIA_PT { get { return _TEXTO_TECNICO_SUPERA_LIMITE_VISITAS_DIA_PT; } set { _TEXTO_TECNICO_SUPERA_LIMITE_VISITAS_DIA = value; } }
public string TEXTO_TELEFONO_DEBE_COMENZAR_6789_PT { get { return _TEXTO_TELEFONO_DEBE_COMENZAR_6789_PT; } set { _TEXTO_TELEFONO_DEBE_COMENZAR_6789 = value; } }
public string TEXTO_TELEFONO_DEBE_TENER_9_DIGITOS_PT { get { return _TEXTO_TELEFONO_DEBE_TENER_9_DIGITOS_PT; } set { _TEXTO_TELEFONO_DEBE_TENER_9_DIGITOS = value; } }
public string TEXTO_TELEFONO_OBLIGATORIO_PT { get { return _TEXTO_TELEFONO_OBLIGATORIO_PT; } set { _TEXTO_TELEFONO_OBLIGATORIO = value; } }
public string TEXTO_TELEFONOS_ACTUALIZADOS_PT { get { return _TEXTO_TELEFONOS_ACTUALIZADOS_PT; } set { _TEXTO_TELEFONOS_ACTUALIZADOS = value; } }
public string TEXTO_TODAS_PT { get { return _TEXTO_TODAS_PT; } set { _TEXTO_TODAS = value; } }
public string TEXTO_TODOS_PT { get { return _TEXTO_TODOS_PT; } set { _TEXTO_TODOS = value; } }
public string TEXTO_VALORACION_CUADRO_MANDO_PT { get { return _TEXTO_VALORACION_CUADRO_MANDO_PT; } set { _TEXTO_VALORACION_CUADRO_MANDO = value; } }
public string TEXTO_VER_HISTORICO_PT { get { return _TEXTO_VER_HISTORICO_PT; } set { _TEXTO_VER_HISTORICO = value; } }
public string TEXTO_VISITA_PT { get { return _TEXTO_VISITA_PT; } set { _TEXTO_VISITA = value; } }
public string TEXTO_VISITA_MODIFICAR_FACTURADA_PT { get { return _TEXTO_VISITA_MODIFICAR_FACTURADA_PT; } set { _TEXTO_VISITA_MODIFICAR_FACTURADA = value; } }
public string TEXTO_VISITA_REALIZADA_PT { get { return _TEXTO_VISITA_REALIZADA_PT; } set { _TEXTO_VISITA_REALIZADA = value; } }
public string TEXTO_VISITA_SUPERVISION_PT { get { return _TEXTO_VISITA_SUPERVISION_PT; } set { _TEXTO_VISITA_SUPERVISION = value; } }
public string TEXTO_VUELVA_A_SELECCIONAR_LA_SOLICITUD_PT { get { return _TEXTO_VUELVA_A_SELECCIONAR_LA_SOLICITUD_PT; } set { _TEXTO_VUELVA_A_SELECCIONAR_LA_SOLICITUD = value; } }
public string TEXTO_YA_LIQUIDADO_CAMBIAR_ESTADO_PT { get { return _TEXTO_YA_LIQUIDADO_CAMBIAR_ESTADO_PT; } set { _TEXTO_YA_LIQUIDADO_CAMBIAR_ESTADO = value; } }
public string TEXTO_YA_LIQUIDADO_ELIMINAR_PT { get { return _TEXTO_YA_LIQUIDADO_ELIMINAR_PT; } set { _TEXTO_YA_LIQUIDADO_ELIMINAR = value; } }
public string TEXZTO_CONTRASENHIA_CADUCADA_PT { get { return _TEXZTO_CONTRASENHIA_CADUCADA_PT; } set { _TEXZTO_CONTRASENHIA_CADUCADA = value; } }
public string HORARIOProveedor_PT { get { return _HORARIOProveedor_PT; } set { _HORARIOProveedor_PT = value; } }

}